"""Monster entries chunk 5 — vendor/nethack/include/monsters.h lines 2538-3212."""
from Nethax.nethax.constants.monsters import (
    MonsterEntry, MonsterSymbol, AttackType, DamageType,
    NO_ATTK,
    # M1_* flags
    M1_FLY, M1_SWIM, M1_AMORPHOUS, M1_WALLWALK, M1_AMPHIBIOUS,
    M1_BREATHLESS, M1_NOTAKE, M1_NOEYES, M1_NOHANDS, M1_NOLIMBS,
    M1_NOHEAD, M1_MINDLESS, M1_HUMANOID, M1_ANIMAL, M1_SLITHY,
    M1_UNSOLID, M1_THICK_HIDE, M1_REGEN, M1_SEE_INVIS,
    M1_TPORT, M1_TPORT_CNTRL, M1_ACID, M1_POIS,
    M1_CARNIVORE, M1_HERBIVORE, M1_OMNIVORE,
    # M2_* flags
    M2_NOPOLY, M2_UNDEAD, M2_WERE, M2_HUMAN, M2_ELF, M2_DEMON,
    M2_MERC, M2_LORD, M2_PRINCE, M2_MINION, M2_SHAPESHIFTER,
    M2_MALE, M2_FEMALE, M2_NEUTER, M2_PNAME,
    M2_HOSTILE, M2_PEACEFUL, M2_WANDER, M2_STALK, M2_NASTY,
    M2_STRONG, M2_GREEDY, M2_JEWELS, M2_COLLECT, M2_MAGIC,
    # M3_* flags
    M3_WANTSAMUL, M3_WANTSBELL, M3_WANTSBOOK, M3_WANTSCAND,
    M3_WAITFORU, M3_CLOSE, M3_COVETOUS, M3_INFRAVISION,
    M3_INFRAVISIBLE, M3_DISPLACES,
    # MR_* resistance bits
    MR_FIRE, MR_COLD, MR_SLEEP, MR_DISINT, MR_ELEC,
    MR_POISON, MR_ACID, MR_STONE,
    # G_* generation flags
    G_UNIQ, G_NOHELL, G_HELL, G_NOGEN, G_SGROUP, G_LGROUP,
    G_GENO, G_NOCORPSE,
    # MS_* sound constants
    MS_SILENT, MS_HISS, MS_WERE, MS_HUMANOID, MS_SELL, MS_GUARD,
    MS_DJINNI, MS_NURSE, MS_ORACLE, MS_PRIEST, MS_SOLDIER,
    MS_IMITATE, MS_CUSS, MS_BRIBE, MS_RIDER, MS_SEDUCE,
    MS_SPELL, MS_GURGLE, MS_ORC, MS_GROWL, MS_WAIL,
    # MZ_* size constants
    MZ_TINY, MZ_SMALL, MZ_MEDIUM, MZ_HUMAN, MZ_LARGE, MZ_HUGE,
    # WT_* weight constants
    WT_HUMAN, WT_ELF,
    # CLR_* colour constants
    CLR_BLACK, CLR_RED, CLR_GREEN, CLR_BROWN, CLR_BLUE,
    CLR_MAGENTA, CLR_CYAN, CLR_GRAY, CLR_ORANGE,
    CLR_BRIGHT_GREEN, CLR_YELLOW, CLR_BRIGHT_BLUE,
    CLR_BRIGHT_MAGENTA, CLR_BRIGHT_CYAN, CLR_WHITE,
    # HI_* colour aliases
    HI_LORD, HI_DOMESTIC, HI_OVERLORD, HI_METAL, HI_GOLD,
    HI_LEATHER, HI_WOOD, HI_PAPER, HI_ZAP,
    # Misc
    A_NONE,
)

# ---------------------------------------------------------------------------
# SEDUCTION_ATTACKS_YES / _NO macros (expanded inline)
# ---------------------------------------------------------------------------
_SEDUCTION_ATTACKS_YES = (
    (AttackType.AT_BITE, DamageType.AD_SSEX, 0, 0),
    (AttackType.AT_CLAW, DamageType.AD_PHYS, 1, 3),
    (AttackType.AT_CLAW, DamageType.AD_PHYS, 1, 3),
    NO_ATTK, NO_ATTK, NO_ATTK,
)

ENTRIES = (
    # 261 — leather golem
    MonsterEntry(
        name="leather golem",
        symbol=MonsterSymbol.S_GOLEM,
        level=6, move_speed=6, ac=6, mr=0, alignment=0,
        generation_mask=G_NOCORPSE | 1,
        attacks=(
            (AttackType.AT_CLAW, DamageType.AD_PHYS, 1, 6),
            (AttackType.AT_CLAW, DamageType.AD_PHYS, 1, 6),
            NO_ATTK, NO_ATTK, NO_ATTK, NO_ATTK,
        ),
        weight=800, nutrition=0, sound=MS_SILENT, size=MZ_LARGE,
        resists_mask=MR_SLEEP | MR_POISON, conveys_mask=0,
        flags1=M1_BREATHLESS | M1_MINDLESS | M1_HUMANOID,
        flags2=M2_HOSTILE | M2_NEUTER, flags3=0,
        color=HI_LEATHER,
        difficulty=7,
    ),
    # 262 — wood golem
    MonsterEntry(
        name="wood golem",
        symbol=MonsterSymbol.S_GOLEM,
        level=7, move_speed=3, ac=4, mr=0, alignment=0,
        generation_mask=G_NOCORPSE | 1,
        attacks=(
            (AttackType.AT_CLAW, DamageType.AD_PHYS, 3, 4),
            NO_ATTK, NO_ATTK, NO_ATTK, NO_ATTK, NO_ATTK,
        ),
        weight=900, nutrition=0, sound=MS_SILENT, size=MZ_LARGE,
        resists_mask=MR_COLD | MR_SLEEP | MR_POISON, conveys_mask=0,
        flags1=M1_BREATHLESS | M1_MINDLESS | M1_HUMANOID | M1_THICK_HIDE,
        flags2=M2_HOSTILE | M2_NEUTER, flags3=0,
        color=HI_WOOD,
        difficulty=8,
    ),
    # 263 — flesh golem
    MonsterEntry(
        name="flesh golem",
        symbol=MonsterSymbol.S_GOLEM,
        level=9, move_speed=8, ac=9, mr=30, alignment=0,
        generation_mask=1,
        attacks=(
            (AttackType.AT_CLAW, DamageType.AD_PHYS, 2, 8),
            (AttackType.AT_CLAW, DamageType.AD_PHYS, 2, 8),
            NO_ATTK, NO_ATTK, NO_ATTK, NO_ATTK,
        ),
        weight=1400, nutrition=600, sound=MS_SILENT, size=MZ_LARGE,
        resists_mask=MR_FIRE | MR_COLD | MR_ELEC | MR_SLEEP | MR_POISON,
        conveys_mask=MR_FIRE | MR_COLD | MR_ELEC | MR_SLEEP | MR_POISON,
        flags1=M1_BREATHLESS | M1_MINDLESS | M1_HUMANOID,
        flags2=M2_HOSTILE | M2_STRONG, flags3=0,
        color=CLR_RED,
        difficulty=10,
    ),
    # 264 — clay golem
    MonsterEntry(
        name="clay golem",
        symbol=MonsterSymbol.S_GOLEM,
        level=11, move_speed=7, ac=7, mr=40, alignment=0,
        generation_mask=G_NOCORPSE | 1,
        attacks=(
            (AttackType.AT_CLAW, DamageType.AD_PHYS, 3, 10),
            NO_ATTK, NO_ATTK, NO_ATTK, NO_ATTK, NO_ATTK,
        ),
        weight=1550, nutrition=0, sound=MS_SILENT, size=MZ_LARGE,
        resists_mask=MR_SLEEP | MR_POISON, conveys_mask=0,
        flags1=M1_BREATHLESS | M1_MINDLESS | M1_HUMANOID | M1_THICK_HIDE,
        flags2=M2_HOSTILE | M2_STRONG, flags3=0,
        color=CLR_BROWN,
        difficulty=12,
    ),
    # 265 — stone golem
    MonsterEntry(
        name="stone golem",
        symbol=MonsterSymbol.S_GOLEM,
        level=14, move_speed=6, ac=5, mr=50, alignment=0,
        generation_mask=G_NOCORPSE | 1,
        attacks=(
            (AttackType.AT_CLAW, DamageType.AD_PHYS, 3, 8),
            NO_ATTK, NO_ATTK, NO_ATTK, NO_ATTK, NO_ATTK,
        ),
        weight=1900, nutrition=0, sound=MS_SILENT, size=MZ_LARGE,
        resists_mask=MR_SLEEP | MR_POISON | MR_STONE, conveys_mask=0,
        flags1=M1_BREATHLESS | M1_MINDLESS | M1_HUMANOID | M1_THICK_HIDE,
        flags2=M2_HOSTILE | M2_STRONG, flags3=0,
        color=CLR_GRAY,
        difficulty=15,
    ),
    # 266 — glass golem
    MonsterEntry(
        name="glass golem",
        symbol=MonsterSymbol.S_GOLEM,
        level=16, move_speed=6, ac=1, mr=50, alignment=0,
        generation_mask=G_NOCORPSE | 1,
        attacks=(
            (AttackType.AT_CLAW, DamageType.AD_PHYS, 2, 8),
            (AttackType.AT_CLAW, DamageType.AD_PHYS, 2, 8),
            NO_ATTK, NO_ATTK, NO_ATTK, NO_ATTK,
        ),
        weight=1800, nutrition=0, sound=MS_SILENT, size=MZ_LARGE,
        resists_mask=MR_SLEEP | MR_POISON | MR_ACID, conveys_mask=0,
        flags1=M1_BREATHLESS | M1_MINDLESS | M1_HUMANOID | M1_THICK_HIDE,
        flags2=M2_HOSTILE | M2_STRONG, flags3=0,
        color=CLR_CYAN,
        difficulty=18,
    ),
    # 267 — iron golem
    MonsterEntry(
        name="iron golem",
        symbol=MonsterSymbol.S_GOLEM,
        level=18, move_speed=6, ac=3, mr=60, alignment=0,
        generation_mask=G_NOCORPSE | 1,
        attacks=(
            (AttackType.AT_WEAP, DamageType.AD_PHYS, 4, 10),
            (AttackType.AT_BREA, DamageType.AD_DRST, 4, 6),
            NO_ATTK, NO_ATTK, NO_ATTK, NO_ATTK,
        ),
        weight=2000, nutrition=0, sound=MS_SILENT, size=MZ_LARGE,
        resists_mask=MR_FIRE | MR_COLD | MR_ELEC | MR_SLEEP | MR_POISON,
        conveys_mask=0,
        flags1=M1_BREATHLESS | M1_MINDLESS | M1_HUMANOID | M1_THICK_HIDE | M1_POIS,
        flags2=M2_HOSTILE | M2_STRONG | M2_COLLECT, flags3=0,
        color=HI_METAL,
        difficulty=22,
    ),
    # 268 — human (placeholder, for corpses)
    MonsterEntry(
        name="human",
        symbol=MonsterSymbol.S_HUMAN,
        level=0, move_speed=12, ac=10, mr=0, alignment=0,
        generation_mask=G_NOGEN,
        attacks=(
            (AttackType.AT_WEAP, DamageType.AD_PHYS, 1, 6),
            NO_ATTK, NO_ATTK, NO_ATTK, NO_ATTK, NO_ATTK,
        ),
        weight=WT_HUMAN, nutrition=400, sound=MS_HUMANOID, size=MZ_HUMAN,
        resists_mask=0, conveys_mask=0,
        flags1=M1_HUMANOID | M1_OMNIVORE,
        flags2=M2_NOPOLY | M2_HUMAN | M2_STRONG | M2_COLLECT,
        flags3=M3_INFRAVISIBLE,
        color=HI_DOMESTIC,
        difficulty=2,
    ),
    # 269 — wererat (human form)
    MonsterEntry(
        name="wererat",
        symbol=MonsterSymbol.S_HUMAN,
        level=2, move_speed=12, ac=10, mr=10, alignment=-7,
        generation_mask=1,
        attacks=(
            (AttackType.AT_WEAP, DamageType.AD_PHYS, 2, 4),
            NO_ATTK, NO_ATTK, NO_ATTK, NO_ATTK, NO_ATTK,
        ),
        weight=WT_HUMAN, nutrition=400, sound=MS_WERE, size=MZ_HUMAN,
        resists_mask=MR_POISON, conveys_mask=0,
        flags1=M1_HUMANOID | M1_POIS | M1_REGEN | M1_OMNIVORE,
        flags2=M2_NOPOLY | M2_WERE | M2_HOSTILE | M2_HUMAN | M2_COLLECT,
        flags3=M3_INFRAVISIBLE,
        color=CLR_BROWN,
        difficulty=3,
    ),
    # 270 — werejackal (human form)
    MonsterEntry(
        name="werejackal",
        symbol=MonsterSymbol.S_HUMAN,
        level=2, move_speed=12, ac=10, mr=10, alignment=-7,
        generation_mask=1,
        attacks=(
            (AttackType.AT_WEAP, DamageType.AD_PHYS, 2, 4),
            NO_ATTK, NO_ATTK, NO_ATTK, NO_ATTK, NO_ATTK,
        ),
        weight=WT_HUMAN, nutrition=400, sound=MS_WERE, size=MZ_HUMAN,
        resists_mask=MR_POISON, conveys_mask=0,
        flags1=M1_HUMANOID | M1_POIS | M1_REGEN | M1_OMNIVORE,
        flags2=M2_NOPOLY | M2_WERE | M2_HOSTILE | M2_HUMAN | M2_COLLECT,
        flags3=M3_INFRAVISIBLE,
        color=CLR_RED,
        difficulty=3,
    ),
    # 271 — werewolf (human form)
    MonsterEntry(
        name="werewolf",
        symbol=MonsterSymbol.S_HUMAN,
        level=5, move_speed=12, ac=10, mr=20, alignment=-7,
        generation_mask=1,
        attacks=(
            (AttackType.AT_WEAP, DamageType.AD_PHYS, 2, 4),
            NO_ATTK, NO_ATTK, NO_ATTK, NO_ATTK, NO_ATTK,
        ),
        weight=WT_HUMAN, nutrition=400, sound=MS_WERE, size=MZ_HUMAN,
        resists_mask=MR_POISON, conveys_mask=0,
        flags1=M1_HUMANOID | M1_POIS | M1_REGEN | M1_OMNIVORE,
        flags2=M2_NOPOLY | M2_WERE | M2_HOSTILE | M2_HUMAN | M2_COLLECT,
        flags3=M3_INFRAVISIBLE,
        color=CLR_ORANGE,
        difficulty=6,
    ),
    # 272 — elf (placeholder, for corpses)
    MonsterEntry(
        name="elf",
        symbol=MonsterSymbol.S_HUMAN,
        level=10, move_speed=12, ac=10, mr=2, alignment=-3,
        generation_mask=G_NOGEN,
        attacks=(
            (AttackType.AT_WEAP, DamageType.AD_PHYS, 1, 8),
            NO_ATTK, NO_ATTK, NO_ATTK, NO_ATTK, NO_ATTK,
        ),
        weight=WT_ELF, nutrition=350, sound=MS_HUMANOID, size=MZ_HUMAN,
        resists_mask=MR_SLEEP, conveys_mask=MR_SLEEP,
        flags1=M1_HUMANOID | M1_OMNIVORE | M1_SEE_INVIS,
        flags2=M2_NOPOLY | M2_ELF | M2_STRONG | M2_COLLECT,
        flags3=M3_INFRAVISION | M3_INFRAVISIBLE,
        color=HI_DOMESTIC,
        difficulty=12,
    ),
    # 273 — Woodland-elf
    MonsterEntry(
        name="Woodland-elf",
        symbol=MonsterSymbol.S_HUMAN,
        level=4, move_speed=12, ac=10, mr=10, alignment=-5,
        generation_mask=G_GENO | G_SGROUP | 2,
        attacks=(
            (AttackType.AT_WEAP, DamageType.AD_PHYS, 2, 4),
            NO_ATTK, NO_ATTK, NO_ATTK, NO_ATTK, NO_ATTK,
        ),
        weight=WT_ELF, nutrition=350, sound=MS_HUMANOID, size=MZ_HUMAN,
        resists_mask=MR_SLEEP, conveys_mask=MR_SLEEP,
        flags1=M1_HUMANOID | M1_OMNIVORE | M1_SEE_INVIS,
        flags2=M2_ELF | M2_COLLECT,
        flags3=M3_INFRAVISIBLE | M3_INFRAVISION,
        color=CLR_GREEN,
        difficulty=6,
    ),
    # 274 — Green-elf
    MonsterEntry(
        name="Green-elf",
        symbol=MonsterSymbol.S_HUMAN,
        level=5, move_speed=12, ac=10, mr=10, alignment=-6,
        generation_mask=G_GENO | G_SGROUP | 2,
        attacks=(
            (AttackType.AT_WEAP, DamageType.AD_PHYS, 2, 4),
            NO_ATTK, NO_ATTK, NO_ATTK, NO_ATTK, NO_ATTK,
        ),
        weight=WT_ELF, nutrition=350, sound=MS_HUMANOID, size=MZ_HUMAN,
        resists_mask=MR_SLEEP, conveys_mask=MR_SLEEP,
        flags1=M1_HUMANOID | M1_OMNIVORE | M1_SEE_INVIS,
        flags2=M2_ELF | M2_COLLECT,
        flags3=M3_INFRAVISIBLE | M3_INFRAVISION,
        color=CLR_BRIGHT_GREEN,
        difficulty=7,
    ),
    # 275 — Grey-elf
    MonsterEntry(
        name="Grey-elf",
        symbol=MonsterSymbol.S_HUMAN,
        level=6, move_speed=12, ac=10, mr=10, alignment=-7,
        generation_mask=G_GENO | G_SGROUP | 2,
        attacks=(
            (AttackType.AT_WEAP, DamageType.AD_PHYS, 2, 4),
            NO_ATTK, NO_ATTK, NO_ATTK, NO_ATTK, NO_ATTK,
        ),
        weight=WT_ELF, nutrition=350, sound=MS_HUMANOID, size=MZ_HUMAN,
        resists_mask=MR_SLEEP, conveys_mask=MR_SLEEP,
        flags1=M1_HUMANOID | M1_OMNIVORE | M1_SEE_INVIS,
        flags2=M2_ELF | M2_COLLECT,
        flags3=M3_INFRAVISIBLE | M3_INFRAVISION,
        color=CLR_GRAY,
        difficulty=8,
    ),
    # 276 — elf-lord (NAMS: "elf-lord"/"elf-lady"/"elf-noble")
    MonsterEntry(
        name="elf-lord",
        symbol=MonsterSymbol.S_HUMAN,
        level=8, move_speed=12, ac=10, mr=20, alignment=-9,
        generation_mask=G_GENO | G_SGROUP | 2,
        attacks=(
            (AttackType.AT_WEAP, DamageType.AD_PHYS, 2, 4),
            (AttackType.AT_WEAP, DamageType.AD_PHYS, 2, 4),
            NO_ATTK, NO_ATTK, NO_ATTK, NO_ATTK,
        ),
        weight=WT_ELF, nutrition=350, sound=MS_HUMANOID, size=MZ_HUMAN,
        resists_mask=MR_SLEEP, conveys_mask=MR_SLEEP,
        flags1=M1_HUMANOID | M1_OMNIVORE | M1_SEE_INVIS,
        flags2=M2_ELF | M2_STRONG | M2_LORD | M2_MALE | M2_COLLECT,
        flags3=M3_INFRAVISIBLE | M3_INFRAVISION,
        color=CLR_BRIGHT_BLUE,
        difficulty=11,
    ),
    # 277 — Elvenking (NAMS: "Elvenking"/"Elvenqueen"/"elven monarch")
    MonsterEntry(
        name="Elvenking",
        symbol=MonsterSymbol.S_HUMAN,
        level=9, move_speed=12, ac=10, mr=25, alignment=-10,
        generation_mask=G_GENO | 1,
        attacks=(
            (AttackType.AT_WEAP, DamageType.AD_PHYS, 2, 4),
            (AttackType.AT_WEAP, DamageType.AD_PHYS, 2, 4),
            NO_ATTK, NO_ATTK, NO_ATTK, NO_ATTK,
        ),
        weight=WT_ELF, nutrition=350, sound=MS_HUMANOID, size=MZ_HUMAN,
        resists_mask=MR_SLEEP, conveys_mask=MR_SLEEP,
        flags1=M1_HUMANOID | M1_OMNIVORE | M1_SEE_INVIS,
        flags2=M2_ELF | M2_STRONG | M2_PRINCE | M2_MALE | M2_COLLECT,
        flags3=M3_INFRAVISIBLE | M3_INFRAVISION,
        color=HI_LORD,
        difficulty=11,
    ),
    # 278 — doppelganger
    MonsterEntry(
        name="doppelganger",
        symbol=MonsterSymbol.S_HUMAN,
        level=9, move_speed=12, ac=5, mr=20, alignment=0,
        generation_mask=G_GENO | 1,
        attacks=(
            (AttackType.AT_WEAP, DamageType.AD_PHYS, 1, 12),
            NO_ATTK, NO_ATTK, NO_ATTK, NO_ATTK, NO_ATTK,
        ),
        weight=WT_HUMAN, nutrition=400, sound=MS_IMITATE, size=MZ_HUMAN,
        resists_mask=MR_SLEEP, conveys_mask=0,
        flags1=M1_HUMANOID | M1_OMNIVORE,
        flags2=M2_NOPOLY | M2_HUMAN | M2_HOSTILE | M2_STRONG | M2_COLLECT | M2_SHAPESHIFTER,
        flags3=M3_INFRAVISIBLE,
        color=HI_DOMESTIC,
        difficulty=11,
    ),
    # 279 — shopkeeper
    MonsterEntry(
        name="shopkeeper",
        symbol=MonsterSymbol.S_HUMAN,
        level=12, move_speed=18, ac=0, mr=50, alignment=0,
        generation_mask=G_NOGEN,
        attacks=(
            (AttackType.AT_WEAP, DamageType.AD_PHYS, 4, 4),
            (AttackType.AT_WEAP, DamageType.AD_PHYS, 4, 4),
            NO_ATTK, NO_ATTK, NO_ATTK, NO_ATTK,
        ),
        weight=WT_HUMAN, nutrition=400, sound=MS_SELL, size=MZ_HUMAN,
        resists_mask=0, conveys_mask=0,
        flags1=M1_HUMANOID | M1_OMNIVORE,
        flags2=M2_NOPOLY | M2_HUMAN | M2_PEACEFUL | M2_STRONG | M2_COLLECT | M2_MAGIC,
        flags3=M3_INFRAVISIBLE,
        color=HI_DOMESTIC,
        difficulty=15,
    ),
    # 280 — guard (vault guard)
    MonsterEntry(
        name="guard",
        symbol=MonsterSymbol.S_HUMAN,
        level=12, move_speed=12, ac=10, mr=40, alignment=10,
        generation_mask=G_NOGEN,
        attacks=(
            (AttackType.AT_WEAP, DamageType.AD_PHYS, 4, 10),
            NO_ATTK, NO_ATTK, NO_ATTK, NO_ATTK, NO_ATTK,
        ),
        weight=WT_HUMAN, nutrition=400, sound=MS_GUARD, size=MZ_HUMAN,
        resists_mask=0, conveys_mask=0,
        flags1=M1_HUMANOID | M1_OMNIVORE,
        flags2=M2_NOPOLY | M2_HUMAN | M2_MERC | M2_PEACEFUL | M2_STRONG | M2_COLLECT,
        flags3=M3_INFRAVISIBLE,
        color=CLR_BLUE,
        difficulty=14,
    ),
    # 281 — prisoner
    MonsterEntry(
        name="prisoner",
        symbol=MonsterSymbol.S_HUMAN,
        level=12, move_speed=12, ac=10, mr=0, alignment=0,
        generation_mask=G_NOGEN,
        attacks=(
            (AttackType.AT_WEAP, DamageType.AD_PHYS, 1, 6),
            NO_ATTK, NO_ATTK, NO_ATTK, NO_ATTK, NO_ATTK,
        ),
        weight=WT_HUMAN, nutrition=400, sound=MS_DJINNI, size=MZ_HUMAN,
        resists_mask=0, conveys_mask=0,
        flags1=M1_HUMANOID | M1_OMNIVORE,
        flags2=M2_NOPOLY | M2_HUMAN | M2_PEACEFUL | M2_STRONG | M2_COLLECT,
        flags3=M3_INFRAVISIBLE | M3_CLOSE,
        color=HI_DOMESTIC,
        difficulty=14,
    ),
    # 282 — Oracle
    MonsterEntry(
        name="Oracle",
        symbol=MonsterSymbol.S_HUMAN,
        level=12, move_speed=0, ac=0, mr=50, alignment=0,
        generation_mask=G_NOGEN | G_UNIQ,
        attacks=(
            (AttackType.AT_NONE, DamageType.AD_MAGM, 0, 4),
            NO_ATTK, NO_ATTK, NO_ATTK, NO_ATTK, NO_ATTK,
        ),
        weight=WT_HUMAN, nutrition=400, sound=MS_ORACLE, size=MZ_HUMAN,
        resists_mask=0, conveys_mask=0,
        flags1=M1_HUMANOID | M1_OMNIVORE,
        flags2=M2_NOPOLY | M2_HUMAN | M2_PEACEFUL | M2_FEMALE,
        flags3=M3_INFRAVISIBLE,
        color=HI_ZAP,
        difficulty=13,
    ),
    # 283 — aligned priest (vendor parity: NLE uses unified "aligned priest")
    MonsterEntry(
        name="aligned priest",
        symbol=MonsterSymbol.S_HUMAN,
        level=12, move_speed=12, ac=10, mr=50, alignment=0,
        generation_mask=G_NOGEN,
        attacks=(
            (AttackType.AT_WEAP, DamageType.AD_PHYS, 4, 10),
            (AttackType.AT_KICK, DamageType.AD_PHYS, 1, 4),
            (AttackType.AT_MAGC, DamageType.AD_CLRC, 0, 0),
            NO_ATTK, NO_ATTK, NO_ATTK,
        ),
        weight=WT_HUMAN, nutrition=400, sound=MS_PRIEST, size=MZ_HUMAN,
        resists_mask=MR_ELEC, conveys_mask=0,
        flags1=M1_HUMANOID | M1_OMNIVORE,
        flags2=M2_NOPOLY | M2_HUMAN | M2_LORD | M2_PEACEFUL | M2_COLLECT,
        flags3=M3_INFRAVISIBLE,
        color=CLR_WHITE,
        difficulty=15,
    ),
    # 284 — high priest (NAMS: "high priest"/"high priestess"/"high cleric")
    MonsterEntry(
        name="high priest",
        symbol=MonsterSymbol.S_HUMAN,
        level=25, move_speed=15, ac=7, mr=70, alignment=0,
        generation_mask=G_NOGEN | G_UNIQ,
        attacks=(
            (AttackType.AT_WEAP, DamageType.AD_PHYS, 4, 10),
            (AttackType.AT_KICK, DamageType.AD_PHYS, 2, 8),
            (AttackType.AT_MAGC, DamageType.AD_CLRC, 2, 8),
            (AttackType.AT_MAGC, DamageType.AD_CLRC, 2, 8),
            NO_ATTK, NO_ATTK,
        ),
        weight=WT_HUMAN, nutrition=400, sound=MS_PRIEST, size=MZ_HUMAN,
        resists_mask=MR_FIRE | MR_ELEC | MR_SLEEP | MR_POISON, conveys_mask=0,
        flags1=M1_HUMANOID | M1_SEE_INVIS | M1_OMNIVORE,
        flags2=M2_NOPOLY | M2_HUMAN | M2_MINION | M2_PRINCE | M2_NASTY | M2_COLLECT | M2_MAGIC,
        flags3=M3_INFRAVISIBLE,
        color=CLR_WHITE,
        difficulty=30,
    ),
    # 285 — soldier
    MonsterEntry(
        name="soldier",
        symbol=MonsterSymbol.S_HUMAN,
        level=6, move_speed=10, ac=10, mr=0, alignment=-2,
        generation_mask=G_SGROUP | G_GENO | 1,
        attacks=(
            (AttackType.AT_WEAP, DamageType.AD_PHYS, 1, 8),
            NO_ATTK, NO_ATTK, NO_ATTK, NO_ATTK, NO_ATTK,
        ),
        weight=WT_HUMAN, nutrition=400, sound=MS_SOLDIER, size=MZ_HUMAN,
        resists_mask=0, conveys_mask=0,
        flags1=M1_HUMANOID | M1_OMNIVORE,
        flags2=M2_NOPOLY | M2_HUMAN | M2_MERC | M2_STALK | M2_HOSTILE | M2_STRONG | M2_COLLECT,
        flags3=M3_INFRAVISIBLE,
        color=CLR_GRAY,
        difficulty=8,
    ),
    # 286 — sergeant
    MonsterEntry(
        name="sergeant",
        symbol=MonsterSymbol.S_HUMAN,
        level=8, move_speed=10, ac=10, mr=5, alignment=-3,
        generation_mask=G_SGROUP | G_GENO | 1,
        attacks=(
            (AttackType.AT_WEAP, DamageType.AD_PHYS, 2, 6),
            NO_ATTK, NO_ATTK, NO_ATTK, NO_ATTK, NO_ATTK,
        ),
        weight=WT_HUMAN, nutrition=400, sound=MS_SOLDIER, size=MZ_HUMAN,
        resists_mask=0, conveys_mask=0,
        flags1=M1_HUMANOID | M1_OMNIVORE,
        flags2=M2_NOPOLY | M2_HUMAN | M2_MERC | M2_STALK | M2_HOSTILE | M2_STRONG | M2_COLLECT,
        flags3=M3_INFRAVISIBLE,
        color=CLR_RED,
        difficulty=10,
    ),
    # 287 — nurse
    MonsterEntry(
        name="nurse",
        symbol=MonsterSymbol.S_HUMAN,
        level=11, move_speed=6, ac=0, mr=0, alignment=0,
        generation_mask=G_GENO | 3,
        attacks=(
            (AttackType.AT_CLAW, DamageType.AD_HEAL, 2, 6),
            NO_ATTK, NO_ATTK, NO_ATTK, NO_ATTK, NO_ATTK,
        ),
        weight=WT_HUMAN, nutrition=400, sound=MS_NURSE, size=MZ_HUMAN,
        resists_mask=MR_POISON, conveys_mask=MR_POISON,
        flags1=M1_HUMANOID | M1_OMNIVORE,
        flags2=M2_NOPOLY | M2_HUMAN | M2_HOSTILE,
        flags3=M3_INFRAVISIBLE,
        color=HI_DOMESTIC,
        difficulty=13,
    ),
    # 288 — lieutenant
    MonsterEntry(
        name="lieutenant",
        symbol=MonsterSymbol.S_HUMAN,
        level=10, move_speed=10, ac=10, mr=15, alignment=-4,
        generation_mask=G_GENO | 1,
        attacks=(
            (AttackType.AT_WEAP, DamageType.AD_PHYS, 3, 4),
            (AttackType.AT_WEAP, DamageType.AD_PHYS, 3, 4),
            NO_ATTK, NO_ATTK, NO_ATTK, NO_ATTK,
        ),
        weight=WT_HUMAN, nutrition=400, sound=MS_SOLDIER, size=MZ_HUMAN,
        resists_mask=0, conveys_mask=0,
        flags1=M1_HUMANOID | M1_OMNIVORE,
        flags2=M2_NOPOLY | M2_HUMAN | M2_MERC | M2_STALK | M2_HOSTILE | M2_STRONG | M2_COLLECT,
        flags3=M3_INFRAVISIBLE,
        color=CLR_GREEN,
        difficulty=12,
    ),
    # 289 — captain
    MonsterEntry(
        name="captain",
        symbol=MonsterSymbol.S_HUMAN,
        level=12, move_speed=10, ac=10, mr=15, alignment=-5,
        generation_mask=G_GENO | 1,
        attacks=(
            (AttackType.AT_WEAP, DamageType.AD_PHYS, 4, 4),
            (AttackType.AT_WEAP, DamageType.AD_PHYS, 4, 4),
            NO_ATTK, NO_ATTK, NO_ATTK, NO_ATTK,
        ),
        weight=WT_HUMAN, nutrition=400, sound=MS_SOLDIER, size=MZ_HUMAN,
        resists_mask=0, conveys_mask=0,
        flags1=M1_HUMANOID | M1_OMNIVORE,
        flags2=M2_NOPOLY | M2_HUMAN | M2_MERC | M2_STALK | M2_HOSTILE | M2_STRONG | M2_COLLECT,
        flags3=M3_INFRAVISIBLE,
        color=CLR_BLUE,
        difficulty=14,
    ),
    # 290 — watchman
    MonsterEntry(
        name="watchman",
        symbol=MonsterSymbol.S_HUMAN,
        level=6, move_speed=10, ac=10, mr=0, alignment=-2,
        generation_mask=G_SGROUP | G_NOGEN | G_GENO | 1,
        attacks=(
            (AttackType.AT_WEAP, DamageType.AD_PHYS, 1, 8),
            NO_ATTK, NO_ATTK, NO_ATTK, NO_ATTK, NO_ATTK,
        ),
        weight=WT_HUMAN, nutrition=400, sound=MS_SOLDIER, size=MZ_HUMAN,
        resists_mask=0, conveys_mask=0,
        flags1=M1_HUMANOID | M1_OMNIVORE,
        flags2=M2_NOPOLY | M2_HUMAN | M2_MERC | M2_STALK | M2_PEACEFUL | M2_STRONG | M2_COLLECT,
        flags3=M3_INFRAVISIBLE,
        color=CLR_GRAY,
        difficulty=8,
    ),
    # 291 — watch captain
    MonsterEntry(
        name="watch captain",
        symbol=MonsterSymbol.S_HUMAN,
        level=10, move_speed=10, ac=10, mr=15, alignment=-4,
        generation_mask=G_NOGEN | G_GENO | 1,
        attacks=(
            (AttackType.AT_WEAP, DamageType.AD_PHYS, 3, 4),
            (AttackType.AT_WEAP, DamageType.AD_PHYS, 3, 4),
            NO_ATTK, NO_ATTK, NO_ATTK, NO_ATTK,
        ),
        weight=WT_HUMAN, nutrition=400, sound=MS_SOLDIER, size=MZ_HUMAN,
        resists_mask=0, conveys_mask=0,
        flags1=M1_HUMANOID | M1_OMNIVORE,
        flags2=M2_NOPOLY | M2_HUMAN | M2_MERC | M2_STALK | M2_PEACEFUL | M2_STRONG | M2_COLLECT,
        flags3=M3_INFRAVISIBLE,
        color=CLR_GREEN,
        difficulty=12,
    ),
    # 292 — Medusa
    MonsterEntry(
        name="Medusa",
        symbol=MonsterSymbol.S_HUMAN,
        level=20, move_speed=12, ac=2, mr=50, alignment=-15,
        generation_mask=G_NOGEN | G_UNIQ,
        attacks=(
            (AttackType.AT_WEAP, DamageType.AD_PHYS, 2, 4),
            (AttackType.AT_CLAW, DamageType.AD_PHYS, 1, 8),
            (AttackType.AT_GAZE, DamageType.AD_STON, 0, 0),
            (AttackType.AT_BITE, DamageType.AD_DRST, 1, 6),
            NO_ATTK, NO_ATTK,
        ),
        weight=WT_HUMAN, nutrition=400, sound=MS_HISS, size=MZ_LARGE,
        resists_mask=MR_POISON | MR_STONE, conveys_mask=MR_POISON | MR_STONE,
        flags1=M1_FLY | M1_SWIM | M1_AMPHIBIOUS | M1_HUMANOID | M1_POIS | M1_OMNIVORE,
        flags2=M2_NOPOLY | M2_HOSTILE | M2_STRONG | M2_PNAME | M2_FEMALE,
        flags3=M3_WAITFORU | M3_INFRAVISIBLE,
        color=CLR_BRIGHT_GREEN,
        difficulty=25,
    ),
    # 293 — Wizard of Yendor
    MonsterEntry(
        name="Wizard of Yendor",
        symbol=MonsterSymbol.S_HUMAN,
        level=30, move_speed=12, ac=-8, mr=100, alignment=A_NONE,
        generation_mask=G_NOGEN | G_UNIQ,
        attacks=(
            (AttackType.AT_CLAW, DamageType.AD_SAMU, 2, 12),
            (AttackType.AT_MAGC, DamageType.AD_SPEL, 0, 0),
            NO_ATTK, NO_ATTK, NO_ATTK, NO_ATTK,
        ),
        weight=WT_HUMAN, nutrition=400, sound=MS_CUSS, size=MZ_HUMAN,
        resists_mask=MR_FIRE | MR_POISON, conveys_mask=MR_FIRE | MR_POISON,
        flags1=M1_FLY | M1_BREATHLESS | M1_HUMANOID | M1_REGEN | M1_SEE_INVIS | M1_TPORT | M1_TPORT_CNTRL | M1_OMNIVORE,
        flags2=M2_NOPOLY | M2_HUMAN | M2_HOSTILE | M2_STRONG | M2_NASTY | M2_PRINCE | M2_MALE | M2_MAGIC,
        flags3=M3_COVETOUS | M3_WAITFORU | M3_INFRAVISIBLE,
        color=CLR_MAGENTA,
        difficulty=34,
    ),
    # 294 — Croesus
    MonsterEntry(
        name="Croesus",
        symbol=MonsterSymbol.S_HUMAN,
        level=20, move_speed=15, ac=0, mr=40, alignment=15,
        generation_mask=G_UNIQ | G_NOGEN,
        attacks=(
            (AttackType.AT_WEAP, DamageType.AD_PHYS, 4, 10),
            NO_ATTK, NO_ATTK, NO_ATTK, NO_ATTK, NO_ATTK,
        ),
        weight=WT_HUMAN, nutrition=400, sound=MS_GUARD, size=MZ_HUMAN,
        resists_mask=0, conveys_mask=0,
        flags1=M1_HUMANOID | M1_SEE_INVIS | M1_OMNIVORE,
        flags2=(M2_NOPOLY | M2_HUMAN | M2_STALK | M2_HOSTILE | M2_STRONG | M2_NASTY
                | M2_PNAME | M2_PRINCE | M2_MALE | M2_GREEDY | M2_JEWELS
                | M2_COLLECT | M2_MAGIC),
        flags3=M3_INFRAVISIBLE,
        color=HI_LORD,
        difficulty=22,
    ),
    # 295 — ghost
    MonsterEntry(
        name="ghost",
        symbol=MonsterSymbol.S_GHOST,
        level=10, move_speed=3, ac=-5, mr=50, alignment=-5,
        generation_mask=G_NOCORPSE | G_NOGEN,
        attacks=(
            (AttackType.AT_TUCH, DamageType.AD_PHYS, 1, 1),
            NO_ATTK, NO_ATTK, NO_ATTK, NO_ATTK, NO_ATTK,
        ),
        weight=WT_HUMAN, nutrition=0, sound=MS_SILENT, size=MZ_HUMAN,
        resists_mask=MR_COLD | MR_DISINT | MR_SLEEP | MR_POISON | MR_STONE,
        conveys_mask=0,
        flags1=M1_FLY | M1_BREATHLESS | M1_WALLWALK | M1_HUMANOID | M1_UNSOLID,
        flags2=M2_NOPOLY | M2_UNDEAD | M2_STALK | M2_HOSTILE,
        flags3=M3_INFRAVISION,
        color=CLR_GRAY,
        difficulty=12,
    ),
    # 296 — shade
    MonsterEntry(
        name="shade",
        symbol=MonsterSymbol.S_GHOST,
        level=12, move_speed=10, ac=10, mr=0, alignment=0,
        generation_mask=G_NOCORPSE | G_NOGEN,
        attacks=(
            (AttackType.AT_TUCH, DamageType.AD_PLYS, 2, 6),
            (AttackType.AT_TUCH, DamageType.AD_SLOW, 1, 6),
            NO_ATTK, NO_ATTK, NO_ATTK, NO_ATTK,
        ),
        weight=WT_HUMAN, nutrition=0, sound=MS_WAIL, size=MZ_HUMAN,
        resists_mask=MR_COLD | MR_DISINT | MR_SLEEP | MR_POISON | MR_STONE,
        conveys_mask=0,
        flags1=M1_FLY | M1_BREATHLESS | M1_WALLWALK | M1_HUMANOID | M1_UNSOLID | M1_SEE_INVIS,
        flags2=M2_NOPOLY | M2_UNDEAD | M2_WANDER | M2_STALK | M2_HOSTILE | M2_NASTY,
        flags3=M3_INFRAVISION,
        color=CLR_BLACK,
        difficulty=14,
    ),
    # 297 — water demon
    MonsterEntry(
        name="water demon",
        symbol=MonsterSymbol.S_DEMON,
        level=8, move_speed=12, ac=-4, mr=30, alignment=-7,
        generation_mask=G_NOCORPSE | G_NOGEN,
        attacks=(
            (AttackType.AT_WEAP, DamageType.AD_PHYS, 1, 3),
            (AttackType.AT_CLAW, DamageType.AD_PHYS, 1, 3),
            (AttackType.AT_BITE, DamageType.AD_PHYS, 1, 3),
            NO_ATTK, NO_ATTK, NO_ATTK,
        ),
        weight=WT_HUMAN, nutrition=400, sound=MS_DJINNI, size=MZ_HUMAN,
        resists_mask=MR_FIRE | MR_POISON, conveys_mask=0,
        flags1=M1_HUMANOID | M1_POIS | M1_SWIM,
        flags2=M2_NOPOLY | M2_DEMON | M2_STALK | M2_HOSTILE | M2_NASTY | M2_COLLECT,
        flags3=M3_INFRAVISIBLE | M3_INFRAVISION,
        color=CLR_BLUE,
        difficulty=11,
    ),
    # 298 — succubus (vendor parity: NLE has separate succubus/incubus)
    MonsterEntry(
        name="succubus",
        symbol=MonsterSymbol.S_DEMON,
        level=6, move_speed=12, ac=0, mr=70, alignment=-9,
        generation_mask=G_NOCORPSE | 1,
        attacks=_SEDUCTION_ATTACKS_YES,
        weight=WT_HUMAN, nutrition=400, sound=MS_SEDUCE, size=MZ_HUMAN,
        resists_mask=MR_FIRE | MR_POISON, conveys_mask=0,
        flags1=M1_HUMANOID | M1_FLY | M1_POIS,
        flags2=M2_DEMON | M2_STALK | M2_HOSTILE | M2_NASTY | M2_FEMALE,
        flags3=M3_INFRAVISIBLE | M3_INFRAVISION,
        color=CLR_GRAY,
        difficulty=8,
    ),
    # 299 — horned devil
    MonsterEntry(
        name="horned devil",
        symbol=MonsterSymbol.S_DEMON,
        level=6, move_speed=9, ac=-5, mr=50, alignment=11,
        generation_mask=G_HELL | G_NOCORPSE | 2,
        attacks=(
            (AttackType.AT_WEAP, DamageType.AD_PHYS, 1, 4),
            (AttackType.AT_CLAW, DamageType.AD_PHYS, 1, 4),
            (AttackType.AT_BITE, DamageType.AD_PHYS, 2, 3),
            (AttackType.AT_STNG, DamageType.AD_PHYS, 1, 3),
            NO_ATTK, NO_ATTK,
        ),
        weight=WT_HUMAN, nutrition=400, sound=MS_SILENT, size=MZ_HUMAN,
        resists_mask=MR_FIRE | MR_POISON, conveys_mask=0,
        flags1=M1_POIS | M1_THICK_HIDE,
        flags2=M2_DEMON | M2_STALK | M2_HOSTILE | M2_NASTY,
        flags3=M3_INFRAVISIBLE | M3_INFRAVISION,
        color=CLR_BROWN,
        difficulty=9,
    ),
    # 300 — incubus (vendor parity: NLE has separate succubus/incubus)
    MonsterEntry(
        name="incubus",
        symbol=MonsterSymbol.S_DEMON,
        level=6, move_speed=12, ac=0, mr=70, alignment=-9,
        generation_mask=G_NOCORPSE | 1,
        attacks=_SEDUCTION_ATTACKS_YES,
        weight=WT_HUMAN, nutrition=400, sound=MS_SEDUCE, size=MZ_HUMAN,
        resists_mask=MR_FIRE | MR_POISON, conveys_mask=0,
        flags1=M1_HUMANOID | M1_FLY | M1_POIS,
        flags2=M2_DEMON | M2_STALK | M2_HOSTILE | M2_NASTY | M2_MALE,
        flags3=M3_INFRAVISIBLE | M3_INFRAVISION,
        color=CLR_GRAY,
        difficulty=8,
    ),
    # 300 — erinys
    MonsterEntry(
        name="erinys",
        symbol=MonsterSymbol.S_DEMON,
        level=7, move_speed=12, ac=2, mr=30, alignment=10,
        generation_mask=G_HELL | G_NOCORPSE | G_SGROUP | 2,
        attacks=(
            (AttackType.AT_WEAP, DamageType.AD_DRST, 2, 4),
            NO_ATTK, NO_ATTK, NO_ATTK, NO_ATTK, NO_ATTK,
        ),
        weight=WT_HUMAN, nutrition=400, sound=MS_SILENT, size=MZ_HUMAN,
        resists_mask=MR_FIRE | MR_POISON, conveys_mask=0,
        flags1=M1_HUMANOID | M1_POIS,
        flags2=M2_NOPOLY | M2_DEMON | M2_STALK | M2_HOSTILE | M2_STRONG | M2_NASTY | M2_FEMALE | M2_COLLECT,
        flags3=M3_INFRAVISIBLE | M3_INFRAVISION,
        color=CLR_RED,
        difficulty=10,
    ),
    # 301 — barbed devil
    MonsterEntry(
        name="barbed devil",
        symbol=MonsterSymbol.S_DEMON,
        level=8, move_speed=12, ac=0, mr=35, alignment=8,
        generation_mask=G_HELL | G_NOCORPSE | G_SGROUP | 2,
        attacks=(
            (AttackType.AT_CLAW, DamageType.AD_PHYS, 2, 4),
            (AttackType.AT_CLAW, DamageType.AD_PHYS, 2, 4),
            (AttackType.AT_STNG, DamageType.AD_PHYS, 3, 4),
            NO_ATTK, NO_ATTK, NO_ATTK,
        ),
        weight=WT_HUMAN, nutrition=400, sound=MS_SILENT, size=MZ_HUMAN,
        resists_mask=MR_FIRE | MR_POISON, conveys_mask=0,
        flags1=M1_POIS | M1_THICK_HIDE,
        flags2=M2_DEMON | M2_STALK | M2_HOSTILE | M2_NASTY,
        flags3=M3_INFRAVISIBLE | M3_INFRAVISION,
        color=CLR_RED,
        difficulty=10,
    ),
    # 302 — marilith
    MonsterEntry(
        name="marilith",
        symbol=MonsterSymbol.S_DEMON,
        level=7, move_speed=12, ac=-6, mr=80, alignment=-12,
        generation_mask=G_HELL | G_NOCORPSE | 1,
        attacks=(
            (AttackType.AT_WEAP, DamageType.AD_PHYS, 2, 4),
            (AttackType.AT_WEAP, DamageType.AD_PHYS, 2, 4),
            (AttackType.AT_CLAW, DamageType.AD_PHYS, 2, 4),
            (AttackType.AT_CLAW, DamageType.AD_PHYS, 2, 4),
            (AttackType.AT_CLAW, DamageType.AD_PHYS, 2, 4),
            (AttackType.AT_CLAW, DamageType.AD_PHYS, 2, 4),
        ),
        weight=WT_HUMAN, nutrition=400, sound=MS_CUSS, size=MZ_LARGE,
        resists_mask=MR_FIRE | MR_POISON, conveys_mask=0,
        flags1=M1_HUMANOID | M1_SLITHY | M1_SEE_INVIS | M1_POIS,
        flags2=M2_DEMON | M2_STALK | M2_HOSTILE | M2_NASTY | M2_FEMALE | M2_COLLECT,
        flags3=M3_INFRAVISIBLE | M3_INFRAVISION,
        color=CLR_RED,
        difficulty=11,
    ),
    # 303 — vrock
    MonsterEntry(
        name="vrock",
        symbol=MonsterSymbol.S_DEMON,
        level=8, move_speed=12, ac=0, mr=50, alignment=-9,
        generation_mask=G_HELL | G_NOCORPSE | G_SGROUP | 2,
        attacks=(
            (AttackType.AT_CLAW, DamageType.AD_PHYS, 1, 4),
            (AttackType.AT_CLAW, DamageType.AD_PHYS, 1, 4),
            (AttackType.AT_CLAW, DamageType.AD_PHYS, 1, 8),
            (AttackType.AT_CLAW, DamageType.AD_PHYS, 1, 8),
            (AttackType.AT_BITE, DamageType.AD_PHYS, 1, 6),
            NO_ATTK,
        ),
        weight=WT_HUMAN, nutrition=400, sound=MS_SILENT, size=MZ_LARGE,
        resists_mask=MR_FIRE | MR_POISON, conveys_mask=0,
        flags1=M1_POIS,
        flags2=M2_DEMON | M2_STALK | M2_HOSTILE | M2_NASTY,
        flags3=M3_INFRAVISIBLE | M3_INFRAVISION,
        color=CLR_RED,
        difficulty=11,
    ),
    # 304 — hezrou
    MonsterEntry(
        name="hezrou",
        symbol=MonsterSymbol.S_DEMON,
        level=9, move_speed=6, ac=-2, mr=55, alignment=-10,
        generation_mask=G_HELL | G_NOCORPSE | G_SGROUP | 2,
        attacks=(
            (AttackType.AT_CLAW, DamageType.AD_PHYS, 1, 3),
            (AttackType.AT_CLAW, DamageType.AD_PHYS, 1, 3),
            (AttackType.AT_BITE, DamageType.AD_PHYS, 4, 4),
            NO_ATTK, NO_ATTK, NO_ATTK,
        ),
        weight=WT_HUMAN, nutrition=400, sound=MS_SILENT, size=MZ_LARGE,
        resists_mask=MR_FIRE | MR_POISON, conveys_mask=0,
        flags1=M1_HUMANOID | M1_POIS,
        flags2=M2_DEMON | M2_STALK | M2_HOSTILE | M2_NASTY,
        flags3=M3_INFRAVISIBLE | M3_INFRAVISION,
        color=CLR_RED,
        difficulty=12,
    ),
    # 305 — bone devil
    MonsterEntry(
        name="bone devil",
        symbol=MonsterSymbol.S_DEMON,
        level=9, move_speed=15, ac=-1, mr=40, alignment=-9,
        generation_mask=G_HELL | G_NOCORPSE | G_SGROUP | 2,
        attacks=(
            (AttackType.AT_WEAP, DamageType.AD_PHYS, 3, 4),
            (AttackType.AT_STNG, DamageType.AD_DRST, 2, 4),
            NO_ATTK, NO_ATTK, NO_ATTK, NO_ATTK,
        ),
        weight=WT_HUMAN, nutrition=400, sound=MS_SILENT, size=MZ_LARGE,
        resists_mask=MR_FIRE | MR_POISON, conveys_mask=0,
        flags1=M1_POIS,
        flags2=M2_DEMON | M2_STALK | M2_HOSTILE | M2_NASTY | M2_COLLECT,
        flags3=M3_INFRAVISIBLE | M3_INFRAVISION,
        color=CLR_GRAY,
        difficulty=13,
    ),
    # 306 — ice devil
    MonsterEntry(
        name="ice devil",
        symbol=MonsterSymbol.S_DEMON,
        level=11, move_speed=6, ac=-4, mr=55, alignment=-12,
        generation_mask=G_HELL | G_NOCORPSE | 2,
        attacks=(
            (AttackType.AT_CLAW, DamageType.AD_PHYS, 1, 4),
            (AttackType.AT_CLAW, DamageType.AD_PHYS, 1, 4),
            (AttackType.AT_BITE, DamageType.AD_PHYS, 2, 4),
            (AttackType.AT_STNG, DamageType.AD_COLD, 3, 4),
            NO_ATTK, NO_ATTK,
        ),
        weight=WT_HUMAN, nutrition=400, sound=MS_SILENT, size=MZ_LARGE,
        resists_mask=MR_FIRE | MR_COLD | MR_POISON, conveys_mask=0,
        flags1=M1_SEE_INVIS | M1_POIS,
        flags2=M2_DEMON | M2_STALK | M2_HOSTILE | M2_NASTY,
        flags3=M3_INFRAVISIBLE | M3_INFRAVISION,
        color=CLR_WHITE,
        difficulty=14,
    ),
    # 307 — nalfeshnee
    MonsterEntry(
        name="nalfeshnee",
        symbol=MonsterSymbol.S_DEMON,
        level=11, move_speed=9, ac=-1, mr=65, alignment=-11,
        generation_mask=G_HELL | G_NOCORPSE | 1,
        attacks=(
            (AttackType.AT_CLAW, DamageType.AD_PHYS, 1, 4),
            (AttackType.AT_CLAW, DamageType.AD_PHYS, 1, 4),
            (AttackType.AT_BITE, DamageType.AD_PHYS, 2, 4),
            (AttackType.AT_MAGC, DamageType.AD_SPEL, 0, 0),
            NO_ATTK, NO_ATTK,
        ),
        weight=WT_HUMAN, nutrition=400, sound=MS_SPELL, size=MZ_LARGE,
        resists_mask=MR_FIRE | MR_POISON, conveys_mask=0,
        flags1=M1_HUMANOID | M1_POIS,
        flags2=M2_DEMON | M2_STALK | M2_HOSTILE | M2_NASTY,
        flags3=M3_INFRAVISIBLE | M3_INFRAVISION,
        color=CLR_RED,
        difficulty=15,
    ),
    # 308 — pit fiend
    MonsterEntry(
        name="pit fiend",
        symbol=MonsterSymbol.S_DEMON,
        level=13, move_speed=6, ac=-3, mr=65, alignment=-13,
        generation_mask=G_HELL | G_NOCORPSE | 2,
        attacks=(
            (AttackType.AT_WEAP, DamageType.AD_PHYS, 4, 2),
            (AttackType.AT_WEAP, DamageType.AD_PHYS, 4, 2),
            (AttackType.AT_HUGS, DamageType.AD_PHYS, 2, 4),
            NO_ATTK, NO_ATTK, NO_ATTK,
        ),
        weight=WT_HUMAN, nutrition=400, sound=MS_GROWL, size=MZ_LARGE,
        resists_mask=MR_FIRE | MR_POISON, conveys_mask=0,
        flags1=M1_SEE_INVIS | M1_POIS,
        flags2=M2_DEMON | M2_STALK | M2_HOSTILE | M2_NASTY | M2_COLLECT,
        flags3=M3_INFRAVISIBLE | M3_INFRAVISION,
        color=CLR_RED,
        difficulty=16,
    ),
    # 309 — sandestin
    MonsterEntry(
        name="sandestin",
        symbol=MonsterSymbol.S_DEMON,
        level=13, move_speed=12, ac=4, mr=60, alignment=-5,
        generation_mask=G_HELL | G_NOCORPSE | 1,
        attacks=(
            (AttackType.AT_WEAP, DamageType.AD_PHYS, 2, 6),
            (AttackType.AT_WEAP, DamageType.AD_PHYS, 2, 6),
            NO_ATTK, NO_ATTK, NO_ATTK, NO_ATTK,
        ),
        weight=1500, nutrition=400, sound=MS_CUSS, size=MZ_HUMAN,
        resists_mask=MR_STONE, conveys_mask=0,
        flags1=M1_HUMANOID,
        flags2=M2_NOPOLY | M2_STALK | M2_STRONG | M2_COLLECT | M2_SHAPESHIFTER,
        flags3=M3_INFRAVISIBLE | M3_INFRAVISION,
        color=CLR_GRAY,
        difficulty=15,
    ),
    # 310 — balrog
    MonsterEntry(
        name="balrog",
        symbol=MonsterSymbol.S_DEMON,
        level=16, move_speed=5, ac=-2, mr=75, alignment=-14,
        generation_mask=G_HELL | G_NOCORPSE | 1,
        attacks=(
            (AttackType.AT_WEAP, DamageType.AD_PHYS, 8, 4),
            (AttackType.AT_WEAP, DamageType.AD_PHYS, 4, 6),
            NO_ATTK, NO_ATTK, NO_ATTK, NO_ATTK,
        ),
        weight=WT_HUMAN, nutrition=400, sound=MS_SILENT, size=MZ_LARGE,
        resists_mask=MR_FIRE | MR_POISON, conveys_mask=0,
        flags1=M1_FLY | M1_SEE_INVIS | M1_POIS,
        flags2=M2_DEMON | M2_STALK | M2_HOSTILE | M2_STRONG | M2_NASTY | M2_COLLECT,
        flags3=M3_INFRAVISIBLE | M3_INFRAVISION,
        color=CLR_RED,
        difficulty=20,
    ),
    # 311 — Juiblex
    MonsterEntry(
        name="Juiblex",
        symbol=MonsterSymbol.S_DEMON,
        level=50, move_speed=3, ac=-7, mr=65, alignment=-15,
        generation_mask=G_HELL | G_NOCORPSE | G_NOGEN | G_UNIQ,
        attacks=(
            (AttackType.AT_ENGL, DamageType.AD_DISE, 4, 10),
            (AttackType.AT_SPIT, DamageType.AD_ACID, 3, 6),
            NO_ATTK, NO_ATTK, NO_ATTK, NO_ATTK,
        ),
        weight=1500, nutrition=0, sound=MS_GURGLE, size=MZ_LARGE,
        resists_mask=MR_FIRE | MR_POISON | MR_ACID | MR_STONE, conveys_mask=0,
        flags1=(M1_AMPHIBIOUS | M1_AMORPHOUS | M1_NOHEAD | M1_FLY | M1_SEE_INVIS
                | M1_ACID | M1_POIS),
        flags2=(M2_NOPOLY | M2_DEMON | M2_STALK | M2_HOSTILE | M2_PNAME | M2_NASTY
                | M2_LORD | M2_MALE),
        flags3=M3_WAITFORU | M3_WANTSAMUL | M3_INFRAVISION,
        color=CLR_BRIGHT_GREEN,
        difficulty=26,
    ),
    # 312 — Yeenoghu
    MonsterEntry(
        name="Yeenoghu",
        symbol=MonsterSymbol.S_DEMON,
        level=56, move_speed=18, ac=-5, mr=80, alignment=-15,
        generation_mask=G_HELL | G_NOCORPSE | G_NOGEN | G_UNIQ,
        attacks=(
            (AttackType.AT_WEAP, DamageType.AD_PHYS, 3, 6),
            (AttackType.AT_WEAP, DamageType.AD_CONF, 2, 8),
            (AttackType.AT_CLAW, DamageType.AD_PLYS, 1, 6),
            (AttackType.AT_MAGC, DamageType.AD_MAGM, 2, 6),
            NO_ATTK, NO_ATTK,
        ),
        weight=900, nutrition=500, sound=MS_ORC, size=MZ_LARGE,
        resists_mask=MR_FIRE | MR_POISON, conveys_mask=0,
        flags1=M1_FLY | M1_SEE_INVIS | M1_POIS,
        flags2=(M2_NOPOLY | M2_DEMON | M2_STALK | M2_HOSTILE | M2_PNAME | M2_NASTY
                | M2_LORD | M2_MALE | M2_COLLECT),
        flags3=M3_WANTSAMUL | M3_INFRAVISIBLE | M3_INFRAVISION,
        color=HI_LORD,
        difficulty=31,
    ),
    # 313 — Orcus
    MonsterEntry(
        name="Orcus",
        symbol=MonsterSymbol.S_DEMON,
        level=66, move_speed=9, ac=-6, mr=85, alignment=-20,
        generation_mask=G_HELL | G_NOCORPSE | G_NOGEN | G_UNIQ,
        attacks=(
            (AttackType.AT_WEAP, DamageType.AD_PHYS, 3, 6),
            (AttackType.AT_CLAW, DamageType.AD_PHYS, 3, 4),
            (AttackType.AT_CLAW, DamageType.AD_PHYS, 3, 4),
            (AttackType.AT_MAGC, DamageType.AD_SPEL, 8, 6),
            (AttackType.AT_STNG, DamageType.AD_DRST, 2, 4),
            NO_ATTK,
        ),
        weight=1500, nutrition=500, sound=MS_ORC, size=MZ_HUGE,
        resists_mask=MR_FIRE | MR_POISON, conveys_mask=0,
        flags1=M1_FLY | M1_SEE_INVIS | M1_POIS,
        flags2=(M2_NOPOLY | M2_DEMON | M2_STALK | M2_HOSTILE | M2_PNAME | M2_NASTY
                | M2_PRINCE | M2_MALE | M2_COLLECT),
        flags3=(M3_WAITFORU | M3_WANTSBOOK | M3_WANTSAMUL | M3_INFRAVISIBLE
                | M3_INFRAVISION),
        color=HI_LORD,
        difficulty=36,
    ),
    # 314 — Geryon
    MonsterEntry(
        name="Geryon",
        symbol=MonsterSymbol.S_DEMON,
        level=72, move_speed=3, ac=-3, mr=75, alignment=15,
        generation_mask=G_HELL | G_NOCORPSE | G_NOGEN | G_UNIQ,
        attacks=(
            (AttackType.AT_CLAW, DamageType.AD_PHYS, 3, 6),
            (AttackType.AT_CLAW, DamageType.AD_PHYS, 3, 6),
            (AttackType.AT_STNG, DamageType.AD_DRST, 2, 4),
            NO_ATTK, NO_ATTK, NO_ATTK,
        ),
        weight=1500, nutrition=500, sound=MS_BRIBE, size=MZ_HUGE,
        resists_mask=MR_FIRE | MR_POISON, conveys_mask=0,
        flags1=M1_FLY | M1_SEE_INVIS | M1_POIS | M1_SLITHY,
        flags2=(M2_NOPOLY | M2_DEMON | M2_STALK | M2_HOSTILE | M2_PNAME | M2_NASTY
                | M2_PRINCE | M2_MALE),
        flags3=M3_WANTSAMUL | M3_INFRAVISIBLE | M3_INFRAVISION,
        color=HI_LORD,
        difficulty=36,
    ),
    # 315 — Dispater
    MonsterEntry(
        name="Dispater",
        symbol=MonsterSymbol.S_DEMON,
        level=78, move_speed=15, ac=-2, mr=80, alignment=15,
        generation_mask=G_HELL | G_NOCORPSE | G_NOGEN | G_UNIQ,
        attacks=(
            (AttackType.AT_WEAP, DamageType.AD_PHYS, 4, 6),
            (AttackType.AT_MAGC, DamageType.AD_SPEL, 6, 6),
            NO_ATTK, NO_ATTK, NO_ATTK, NO_ATTK,
        ),
        weight=1500, nutrition=500, sound=MS_BRIBE, size=MZ_HUMAN,
        resists_mask=MR_FIRE | MR_POISON, conveys_mask=0,
        flags1=M1_FLY | M1_SEE_INVIS | M1_POIS | M1_HUMANOID,
        flags2=(M2_NOPOLY | M2_DEMON | M2_STALK | M2_HOSTILE | M2_PNAME | M2_NASTY
                | M2_PRINCE | M2_MALE | M2_COLLECT),
        flags3=M3_WANTSAMUL | M3_INFRAVISIBLE | M3_INFRAVISION,
        color=HI_LORD,
        difficulty=40,
    ),
    # 316 — Baalzebub
    MonsterEntry(
        name="Baalzebub",
        symbol=MonsterSymbol.S_DEMON,
        level=89, move_speed=9, ac=-5, mr=85, alignment=20,
        generation_mask=G_HELL | G_NOCORPSE | G_NOGEN | G_UNIQ,
        attacks=(
            (AttackType.AT_BITE, DamageType.AD_DRST, 2, 6),
            (AttackType.AT_GAZE, DamageType.AD_STUN, 2, 6),
            NO_ATTK, NO_ATTK, NO_ATTK, NO_ATTK,
        ),
        weight=1500, nutrition=500, sound=MS_BRIBE, size=MZ_LARGE,
        resists_mask=MR_FIRE | MR_POISON, conveys_mask=0,
        flags1=M1_FLY | M1_SEE_INVIS | M1_POIS,
        flags2=(M2_NOPOLY | M2_DEMON | M2_STALK | M2_HOSTILE | M2_PNAME | M2_NASTY
                | M2_PRINCE | M2_MALE),
        flags3=M3_WANTSAMUL | M3_WAITFORU | M3_INFRAVISIBLE | M3_INFRAVISION,
        color=HI_LORD,
        difficulty=45,
    ),
    # 317 — Asmodeus
    MonsterEntry(
        name="Asmodeus",
        symbol=MonsterSymbol.S_DEMON,
        level=105, move_speed=12, ac=-7, mr=90, alignment=20,
        generation_mask=G_HELL | G_NOCORPSE | G_NOGEN | G_UNIQ,
        attacks=(
            (AttackType.AT_CLAW, DamageType.AD_PHYS, 4, 4),
            (AttackType.AT_MAGC, DamageType.AD_COLD, 6, 6),
            NO_ATTK, NO_ATTK, NO_ATTK, NO_ATTK,
        ),
        weight=1500, nutrition=500, sound=MS_BRIBE, size=MZ_HUGE,
        resists_mask=MR_FIRE | MR_COLD | MR_POISON, conveys_mask=0,
        flags1=M1_FLY | M1_SEE_INVIS | M1_HUMANOID | M1_POIS,
        flags2=(M2_NOPOLY | M2_DEMON | M2_STALK | M2_HOSTILE | M2_PNAME | M2_STRONG
                | M2_NASTY | M2_PRINCE | M2_MALE),
        flags3=M3_WANTSAMUL | M3_WAITFORU | M3_INFRAVISIBLE | M3_INFRAVISION,
        color=HI_LORD,
        difficulty=53,
    ),
    # 318 — Demogorgon
    MonsterEntry(
        name="Demogorgon",
        symbol=MonsterSymbol.S_DEMON,
        level=106, move_speed=15, ac=-8, mr=95, alignment=-20,
        generation_mask=G_HELL | G_NOCORPSE | G_NOGEN | G_UNIQ,
        attacks=(
            (AttackType.AT_MAGC, DamageType.AD_SPEL, 8, 6),
            (AttackType.AT_STNG, DamageType.AD_DRLI, 1, 4),
            (AttackType.AT_CLAW, DamageType.AD_DISE, 1, 6),
            (AttackType.AT_CLAW, DamageType.AD_DISE, 1, 6),
            NO_ATTK, NO_ATTK,
        ),
        weight=1500, nutrition=500, sound=MS_GROWL, size=MZ_HUGE,
        resists_mask=MR_FIRE | MR_POISON, conveys_mask=0,
        flags1=M1_FLY | M1_SEE_INVIS | M1_NOHANDS | M1_POIS,
        flags2=(M2_NOPOLY | M2_DEMON | M2_STALK | M2_HOSTILE | M2_PNAME | M2_NASTY
                | M2_PRINCE | M2_MALE),
        flags3=M3_WANTSAMUL | M3_INFRAVISIBLE | M3_INFRAVISION,
        color=HI_LORD,
        difficulty=57,
    ),
    # 319 — Death (Rider)
    MonsterEntry(
        name="Death",
        symbol=MonsterSymbol.S_DEMON,
        level=30, move_speed=12, ac=-5, mr=100, alignment=0,
        generation_mask=G_UNIQ | G_NOGEN,
        attacks=(
            (AttackType.AT_TUCH, DamageType.AD_DETH, 8, 8),
            (AttackType.AT_TUCH, DamageType.AD_DETH, 8, 8),
            NO_ATTK, NO_ATTK, NO_ATTK, NO_ATTK,
        ),
        weight=WT_HUMAN, nutrition=1, sound=MS_RIDER, size=MZ_HUMAN,
        resists_mask=MR_FIRE | MR_COLD | MR_ELEC | MR_SLEEP | MR_POISON | MR_STONE,
        conveys_mask=0,
        flags1=M1_FLY | M1_HUMANOID | M1_REGEN | M1_SEE_INVIS | M1_TPORT_CNTRL,
        flags2=M2_NOPOLY | M2_STALK | M2_HOSTILE | M2_PNAME | M2_STRONG | M2_NASTY,
        flags3=M3_INFRAVISIBLE | M3_INFRAVISION | M3_DISPLACES,
        color=HI_LORD,
        difficulty=34,
    ),
    # 320 — Pestilence (Rider)
    MonsterEntry(
        name="Pestilence",
        symbol=MonsterSymbol.S_DEMON,
        level=30, move_speed=12, ac=-5, mr=100, alignment=0,
        generation_mask=G_UNIQ | G_NOGEN,
        attacks=(
            (AttackType.AT_TUCH, DamageType.AD_PEST, 8, 8),
            (AttackType.AT_TUCH, DamageType.AD_PEST, 8, 8),
            NO_ATTK, NO_ATTK, NO_ATTK, NO_ATTK,
        ),
        weight=WT_HUMAN, nutrition=1, sound=MS_RIDER, size=MZ_HUMAN,
        resists_mask=MR_FIRE | MR_COLD | MR_ELEC | MR_SLEEP | MR_POISON | MR_STONE,
        conveys_mask=0,
        flags1=M1_FLY | M1_HUMANOID | M1_REGEN | M1_SEE_INVIS | M1_TPORT_CNTRL,
        flags2=M2_NOPOLY | M2_STALK | M2_HOSTILE | M2_PNAME | M2_STRONG | M2_NASTY,
        flags3=M3_INFRAVISIBLE | M3_INFRAVISION | M3_DISPLACES,
        color=HI_LORD,
        difficulty=34,
    ),
    # 321 — Famine (Rider)
    MonsterEntry(
        name="Famine",
        symbol=MonsterSymbol.S_DEMON,
        level=30, move_speed=12, ac=-5, mr=100, alignment=0,
        generation_mask=G_UNIQ | G_NOGEN,
        attacks=(
            (AttackType.AT_TUCH, DamageType.AD_FAMN, 8, 8),
            (AttackType.AT_TUCH, DamageType.AD_FAMN, 8, 8),
            NO_ATTK, NO_ATTK, NO_ATTK, NO_ATTK,
        ),
        weight=WT_HUMAN, nutrition=1, sound=MS_RIDER, size=MZ_HUMAN,
        resists_mask=MR_FIRE | MR_COLD | MR_ELEC | MR_SLEEP | MR_POISON | MR_STONE,
        conveys_mask=0,
        flags1=M1_FLY | M1_HUMANOID | M1_REGEN | M1_SEE_INVIS | M1_TPORT_CNTRL,
        flags2=M2_NOPOLY | M2_STALK | M2_HOSTILE | M2_PNAME | M2_STRONG | M2_NASTY,
        flags3=M3_INFRAVISIBLE | M3_INFRAVISION | M3_DISPLACES,
        color=HI_LORD,
        difficulty=34,
    ),
)
