"""Monster entries chunk 2 — vendor/nethack/include/monsters.h lines 679-1275.

Entries 65-126 (0-indexed): large mimic through bat.
"""
from Nethax.nethax.constants.monsters import (
    MonsterEntry, MonsterSymbol, AttackType, DamageType,
    G_GENO, G_NOGEN, G_NOCORPSE, G_SGROUP, G_LGROUP, G_NOHELL, G_HELL, G_UNIQ,
    MR_FIRE, MR_COLD, MR_SLEEP, MR_DISINT, MR_ELEC, MR_POISON, MR_ACID, MR_STONE,
    MS_SILENT, MS_BARK, MS_MEW, MS_ROAR, MS_BELLOW, MS_GROWL, MS_SQEEK, MS_SQAWK,
    MS_CHIRP, MS_HISS, MS_BUZZ, MS_GRUNT, MS_NEIGH, MS_MOO, MS_WAIL, MS_GURGLE,
    MS_BURBLE, MS_TRUMPET, MS_SHRIEK, MS_BONES, MS_LAUGH, MS_MUMBLE, MS_IMITATE,
    MS_WERE, MS_ORC, MS_HUMANOID, MS_ARREST, MS_SOLDIER, MS_GUARD, MS_DJINNI,
    MS_NURSE, MS_SEDUCE, MS_VAMPIRE, MS_BRIBE, MS_CUSS, MS_RIDER, MS_LEADER,
    MS_NEMESIS, MS_GUARDIAN, MS_SELL, MS_ORACLE, MS_PRIEST, MS_SPELL, MS_BOAST,
    MS_GROAN,
    MZ_TINY, MZ_SMALL, MZ_MEDIUM, MZ_HUMAN, MZ_LARGE, MZ_HUGE, MZ_GIGANTIC,
    M1_FLY, M1_SWIM, M1_AMORPHOUS, M1_WALLWALK, M1_CLING, M1_TUNNEL,
    M1_NEEDPICK, M1_CONCEAL, M1_HIDE, M1_AMPHIBIOUS, M1_BREATHLESS, M1_NOTAKE,
    M1_NOEYES, M1_NOHANDS, M1_NOLIMBS, M1_NOHEAD, M1_MINDLESS, M1_HUMANOID,
    M1_ANIMAL, M1_SLITHY, M1_UNSOLID, M1_THICK_HIDE, M1_OVIPAROUS, M1_REGEN,
    M1_SEE_INVIS, M1_TPORT, M1_TPORT_CNTRL, M1_ACID, M1_POIS,
    M1_CARNIVORE, M1_HERBIVORE, M1_OMNIVORE, M1_METALLIVORE,
    M2_NOPOLY, M2_UNDEAD, M2_WERE, M2_HUMAN, M2_ELF, M2_DWARF, M2_GNOME,
    M2_ORC, M2_DEMON, M2_MERC, M2_LORD, M2_PRINCE, M2_MINION, M2_GIANT,
    M2_SHAPESHIFTER, M2_MALE, M2_FEMALE, M2_NEUTER, M2_PNAME, M2_HOSTILE,
    M2_PEACEFUL, M2_DOMESTIC, M2_WANDER, M2_STALK, M2_NASTY, M2_STRONG,
    M2_ROCKTHROW, M2_GREEDY, M2_JEWELS, M2_COLLECT, M2_MAGIC,
    M3_WANTSAMUL, M3_WANTSBELL, M3_WANTSBOOK, M3_WANTSCAND, M3_WANTSARTI,
    M3_WANTSALL, M3_WAITFORU, M3_CLOSE, M3_COVETOUS, M3_INFRAVISION,
    M3_INFRAVISIBLE, M3_DISPLACES,
    WT_ETHEREAL, WT_JELLY, WT_NYMPH, WT_ELF, WT_HUMAN, WT_BABY_DRAGON,
    WT_DRAGON,
    CLR_BLACK, CLR_RED, CLR_GREEN, CLR_BROWN, CLR_BLUE, CLR_MAGENTA, CLR_CYAN,
    CLR_GRAY, NO_COLOR, CLR_ORANGE, CLR_BRIGHT_GREEN, CLR_YELLOW,
    CLR_BRIGHT_BLUE, CLR_BRIGHT_MAGENTA, CLR_BRIGHT_CYAN, CLR_WHITE,
    HI_LORD, HI_DOMESTIC, HI_OVERLORD, HI_METAL, HI_GOLD, HI_LEATHER,
    HI_WOOD, HI_PAPER, HI_GLASS, HI_ZAP, DRAGON_SILVER,
    A_NONE,
)

ENTRIES = (
    # 65 — large mimic
    MonsterEntry(
        name="large mimic", symbol=MonsterSymbol.S_MIMIC,
        level=8, move_speed=3, ac=7, mr=10, alignment=0,
        generation_mask=G_GENO | 1,
        attacks=(
            (AttackType.AT_CLAW, DamageType.AD_STCK, 3, 4),
        ),
        weight=600, nutrition=400, sound=MS_SILENT, size=MZ_LARGE,
        resists_mask=MR_ACID, conveys_mask=0,
        flags1=M1_CLING | M1_BREATHLESS | M1_AMORPHOUS | M1_HIDE | M1_ANIMAL
            | M1_NOEYES | M1_NOHEAD | M1_NOLIMBS | M1_THICK_HIDE | M1_CARNIVORE,
        flags2=M2_HOSTILE | M2_STRONG,
        flags3=0,
        color=CLR_RED,
        difficulty=9,
    ),
    # 70 — giant mimic
    MonsterEntry(
        name="giant mimic", symbol=MonsterSymbol.S_MIMIC,
        level=9, move_speed=3, ac=7, mr=20, alignment=0,
        generation_mask=G_GENO | 1,
        attacks=(
            (AttackType.AT_CLAW, DamageType.AD_STCK, 3, 6),
            (AttackType.AT_CLAW, DamageType.AD_STCK, 3, 6),
        ),
        weight=800, nutrition=500, sound=MS_SILENT, size=MZ_LARGE,
        resists_mask=MR_ACID, conveys_mask=0,
        flags1=M1_CLING | M1_BREATHLESS | M1_AMORPHOUS | M1_HIDE | M1_ANIMAL
            | M1_NOEYES | M1_NOHEAD | M1_NOLIMBS | M1_THICK_HIDE | M1_CARNIVORE,
        flags2=M2_HOSTILE | M2_STRONG,
        flags3=0,
        color=HI_LORD,
        difficulty=11,
    ),
    # 71 — wood nymph
    MonsterEntry(
        name="wood nymph", symbol=MonsterSymbol.S_NYMPH,
        level=3, move_speed=12, ac=9, mr=20, alignment=0,
        generation_mask=G_GENO | 2,
        attacks=(
            (AttackType.AT_CLAW, DamageType.AD_SITM, 0, 0),
            (AttackType.AT_CLAW, DamageType.AD_SEDU, 0, 0),
        ),
        weight=WT_NYMPH, nutrition=300, sound=MS_SEDUCE, size=MZ_HUMAN,
        resists_mask=0, conveys_mask=0,
        flags1=M1_HUMANOID | M1_TPORT,
        flags2=M2_HOSTILE | M2_FEMALE | M2_COLLECT,
        flags3=M3_INFRAVISIBLE,
        color=CLR_GREEN,
        difficulty=5,
    ),
    # 72 — water nymph
    MonsterEntry(
        name="water nymph", symbol=MonsterSymbol.S_NYMPH,
        level=3, move_speed=12, ac=9, mr=20, alignment=0,
        generation_mask=G_GENO | 2,
        attacks=(
            (AttackType.AT_CLAW, DamageType.AD_SITM, 0, 0),
            (AttackType.AT_CLAW, DamageType.AD_SEDU, 0, 0),
        ),
        weight=WT_NYMPH, nutrition=300, sound=MS_SEDUCE, size=MZ_HUMAN,
        resists_mask=0, conveys_mask=0,
        flags1=M1_HUMANOID | M1_TPORT | M1_SWIM,
        flags2=M2_HOSTILE | M2_FEMALE | M2_COLLECT,
        flags3=M3_INFRAVISIBLE,
        color=CLR_BLUE,
        difficulty=5,
    ),
    # 73 — mountain nymph
    MonsterEntry(
        name="mountain nymph", symbol=MonsterSymbol.S_NYMPH,
        level=3, move_speed=12, ac=9, mr=20, alignment=0,
        generation_mask=G_GENO | 2,
        attacks=(
            (AttackType.AT_CLAW, DamageType.AD_SITM, 0, 0),
            (AttackType.AT_CLAW, DamageType.AD_SEDU, 0, 0),
        ),
        weight=WT_NYMPH, nutrition=300, sound=MS_SEDUCE, size=MZ_HUMAN,
        resists_mask=0, conveys_mask=0,
        flags1=M1_HUMANOID | M1_TPORT,
        flags2=M2_HOSTILE | M2_FEMALE | M2_COLLECT,
        flags3=M3_INFRAVISIBLE,
        color=CLR_BROWN,
        difficulty=5,
    ),
    # 74 — goblin
    MonsterEntry(
        name="goblin", symbol=MonsterSymbol.S_ORC,
        level=0, move_speed=6, ac=10, mr=0, alignment=-3,
        generation_mask=G_GENO | 2,
        attacks=(
            (AttackType.AT_WEAP, DamageType.AD_PHYS, 1, 4),
        ),
        weight=400, nutrition=100, sound=MS_ORC, size=MZ_SMALL,
        resists_mask=0, conveys_mask=0,
        flags1=M1_HUMANOID | M1_OMNIVORE,
        flags2=M2_ORC | M2_COLLECT,
        flags3=M3_INFRAVISIBLE | M3_INFRAVISION,
        color=CLR_GRAY,
        difficulty=1,
    ),
    # 75 — hobgoblin
    MonsterEntry(
        name="hobgoblin", symbol=MonsterSymbol.S_ORC,
        level=1, move_speed=9, ac=10, mr=0, alignment=-4,
        generation_mask=G_GENO | 2,
        attacks=(
            (AttackType.AT_WEAP, DamageType.AD_PHYS, 1, 6),
        ),
        weight=1000, nutrition=200, sound=MS_ORC, size=MZ_HUMAN,
        resists_mask=0, conveys_mask=0,
        flags1=M1_HUMANOID | M1_OMNIVORE,
        flags2=M2_ORC | M2_STRONG | M2_COLLECT,
        flags3=M3_INFRAVISIBLE | M3_INFRAVISION,
        color=CLR_BROWN,
        difficulty=3,
    ),
    # 76 — orc
    MonsterEntry(
        name="orc", symbol=MonsterSymbol.S_ORC,
        level=1, move_speed=9, ac=10, mr=0, alignment=-3,
        generation_mask=G_GENO | G_NOGEN | G_LGROUP,
        attacks=(
            (AttackType.AT_WEAP, DamageType.AD_PHYS, 1, 8),
        ),
        weight=850, nutrition=150, sound=MS_ORC, size=MZ_HUMAN,
        resists_mask=0, conveys_mask=0,
        flags1=M1_HUMANOID | M1_OMNIVORE,
        flags2=M2_NOPOLY | M2_ORC | M2_STRONG | M2_GREEDY | M2_JEWELS | M2_COLLECT,
        flags3=M3_INFRAVISIBLE | M3_INFRAVISION,
        color=CLR_RED,
        difficulty=3,
    ),
    # 77 — hill orc
    MonsterEntry(
        name="hill orc", symbol=MonsterSymbol.S_ORC,
        level=2, move_speed=9, ac=10, mr=0, alignment=-4,
        generation_mask=G_GENO | G_LGROUP | 2,
        attacks=(
            (AttackType.AT_WEAP, DamageType.AD_PHYS, 1, 6),
        ),
        weight=1000, nutrition=200, sound=MS_ORC, size=MZ_HUMAN,
        resists_mask=0, conveys_mask=0,
        flags1=M1_HUMANOID | M1_OMNIVORE,
        flags2=M2_ORC | M2_STRONG | M2_GREEDY | M2_JEWELS | M2_COLLECT,
        flags3=M3_INFRAVISIBLE | M3_INFRAVISION,
        color=CLR_YELLOW,
        difficulty=4,
    ),
    # 78 — Mordor orc
    MonsterEntry(
        name="Mordor orc", symbol=MonsterSymbol.S_ORC,
        level=3, move_speed=5, ac=10, mr=0, alignment=-5,
        generation_mask=G_GENO | G_LGROUP | 1,
        attacks=(
            (AttackType.AT_WEAP, DamageType.AD_PHYS, 1, 6),
        ),
        weight=1200, nutrition=200, sound=MS_ORC, size=MZ_HUMAN,
        resists_mask=0, conveys_mask=0,
        flags1=M1_HUMANOID | M1_OMNIVORE,
        flags2=M2_ORC | M2_STRONG | M2_GREEDY | M2_JEWELS | M2_COLLECT,
        flags3=M3_INFRAVISIBLE | M3_INFRAVISION,
        color=CLR_BLUE,
        difficulty=5,
    ),
    # 79 — Uruk-hai
    MonsterEntry(
        name="Uruk-hai", symbol=MonsterSymbol.S_ORC,
        level=3, move_speed=7, ac=10, mr=0, alignment=-4,
        generation_mask=G_GENO | G_LGROUP | 1,
        attacks=(
            (AttackType.AT_WEAP, DamageType.AD_PHYS, 1, 8),
        ),
        weight=1300, nutrition=300, sound=MS_ORC, size=MZ_HUMAN,
        resists_mask=0, conveys_mask=0,
        flags1=M1_HUMANOID | M1_OMNIVORE,
        flags2=M2_ORC | M2_STRONG | M2_GREEDY | M2_JEWELS | M2_COLLECT,
        flags3=M3_INFRAVISIBLE | M3_INFRAVISION,
        color=CLR_BLACK,
        difficulty=5,
    ),
    # 80 — orc shaman
    MonsterEntry(
        name="orc shaman", symbol=MonsterSymbol.S_ORC,
        level=3, move_speed=9, ac=5, mr=10, alignment=-5,
        generation_mask=G_GENO | 1,
        attacks=(
            (AttackType.AT_MAGC, DamageType.AD_SPEL, 0, 0),
        ),
        weight=1000, nutrition=300, sound=MS_ORC, size=MZ_HUMAN,
        resists_mask=0, conveys_mask=0,
        flags1=M1_HUMANOID | M1_OMNIVORE,
        flags2=M2_ORC | M2_STRONG | M2_GREEDY | M2_JEWELS | M2_MAGIC,
        flags3=M3_INFRAVISIBLE | M3_INFRAVISION,
        color=HI_ZAP,
        difficulty=5,
    ),
    # 81 — orc-captain
    MonsterEntry(
        name="orc-captain", symbol=MonsterSymbol.S_ORC,
        level=5, move_speed=5, ac=10, mr=0, alignment=-5,
        generation_mask=G_GENO | 1,
        attacks=(
            (AttackType.AT_WEAP, DamageType.AD_PHYS, 2, 4),
            (AttackType.AT_WEAP, DamageType.AD_PHYS, 2, 4),
        ),
        weight=1350, nutrition=350, sound=MS_ORC, size=MZ_HUMAN,
        resists_mask=0, conveys_mask=0,
        flags1=M1_HUMANOID | M1_OMNIVORE,
        flags2=M2_ORC | M2_STRONG | M2_GREEDY | M2_JEWELS | M2_COLLECT,
        flags3=M3_INFRAVISIBLE | M3_INFRAVISION,
        color=HI_LORD,
        difficulty=7,
    ),
    # 82 — rock piercer
    MonsterEntry(
        name="rock piercer", symbol=MonsterSymbol.S_PIERCER,
        level=3, move_speed=1, ac=3, mr=0, alignment=0,
        generation_mask=G_GENO | 4,
        attacks=(
            (AttackType.AT_BITE, DamageType.AD_PHYS, 2, 6),
        ),
        weight=200, nutrition=200, sound=MS_SILENT, size=MZ_SMALL,
        resists_mask=0, conveys_mask=0,
        flags1=M1_CLING | M1_HIDE | M1_ANIMAL | M1_NOEYES | M1_NOLIMBS
            | M1_CARNIVORE | M1_NOTAKE,
        flags2=M2_HOSTILE,
        flags3=0,
        color=CLR_GRAY,
        difficulty=4,
    ),
    # 83 — iron piercer
    MonsterEntry(
        name="iron piercer", symbol=MonsterSymbol.S_PIERCER,
        level=5, move_speed=1, ac=0, mr=0, alignment=0,
        generation_mask=G_GENO | 2,
        attacks=(
            (AttackType.AT_BITE, DamageType.AD_PHYS, 3, 6),
        ),
        weight=400, nutrition=300, sound=MS_SILENT, size=MZ_MEDIUM,
        resists_mask=0, conveys_mask=0,
        flags1=M1_CLING | M1_HIDE | M1_ANIMAL | M1_NOEYES | M1_NOLIMBS
            | M1_CARNIVORE | M1_NOTAKE,
        flags2=M2_HOSTILE,
        flags3=0,
        color=CLR_CYAN,
        difficulty=6,
    ),
    # 84 — glass piercer
    MonsterEntry(
        name="glass piercer", symbol=MonsterSymbol.S_PIERCER,
        level=7, move_speed=1, ac=0, mr=0, alignment=0,
        generation_mask=G_GENO | 1,
        attacks=(
            (AttackType.AT_BITE, DamageType.AD_PHYS, 4, 6),
        ),
        weight=400, nutrition=300, sound=MS_SILENT, size=MZ_MEDIUM,
        resists_mask=MR_ACID, conveys_mask=0,
        flags1=M1_CLING | M1_HIDE | M1_ANIMAL | M1_NOEYES | M1_NOLIMBS
            | M1_CARNIVORE | M1_NOTAKE,
        flags2=M2_HOSTILE,
        flags3=0,
        color=CLR_WHITE,
        difficulty=9,
    ),
    # 85 — rothe
    MonsterEntry(
        name="rothe", symbol=MonsterSymbol.S_QUADRUPED,
        level=2, move_speed=9, ac=7, mr=0, alignment=0,
        generation_mask=G_GENO | G_SGROUP | 4,
        attacks=(
            (AttackType.AT_CLAW, DamageType.AD_PHYS, 1, 3),
            (AttackType.AT_BITE, DamageType.AD_PHYS, 1, 3),
            (AttackType.AT_BITE, DamageType.AD_PHYS, 1, 8),
        ),
        weight=400, nutrition=100, sound=MS_SILENT, size=MZ_LARGE,
        resists_mask=0, conveys_mask=0,
        flags1=M1_ANIMAL | M1_NOHANDS | M1_OMNIVORE,
        flags2=M2_HOSTILE,
        flags3=M3_INFRAVISIBLE,
        color=CLR_BROWN,
        difficulty=4,
    ),
    # 86 — mumak
    MonsterEntry(
        name="mumak", symbol=MonsterSymbol.S_QUADRUPED,
        level=5, move_speed=9, ac=0, mr=0, alignment=-2,
        generation_mask=G_GENO | 1,
        attacks=(
            (AttackType.AT_BUTT, DamageType.AD_PHYS, 4, 12),
            (AttackType.AT_BITE, DamageType.AD_PHYS, 2, 6),
        ),
        weight=2500, nutrition=500, sound=MS_ROAR, size=MZ_LARGE,
        resists_mask=0, conveys_mask=0,
        flags1=M1_ANIMAL | M1_THICK_HIDE | M1_NOHANDS | M1_HERBIVORE,
        flags2=M2_HOSTILE | M2_STRONG,
        flags3=M3_INFRAVISIBLE,
        color=CLR_GRAY,
        difficulty=7,
    ),
    # 87 — leocrotta
    MonsterEntry(
        name="leocrotta", symbol=MonsterSymbol.S_QUADRUPED,
        level=6, move_speed=18, ac=4, mr=10, alignment=0,
        generation_mask=G_GENO | 2,
        attacks=(
            (AttackType.AT_CLAW, DamageType.AD_PHYS, 2, 6),
            (AttackType.AT_BITE, DamageType.AD_PHYS, 2, 6),
            (AttackType.AT_CLAW, DamageType.AD_PHYS, 2, 6),
        ),
        weight=1200, nutrition=500, sound=MS_IMITATE, size=MZ_LARGE,
        resists_mask=0, conveys_mask=0,
        flags1=M1_ANIMAL | M1_NOHANDS | M1_OMNIVORE,
        flags2=M2_HOSTILE | M2_STRONG,
        flags3=M3_INFRAVISIBLE,
        color=CLR_RED,
        difficulty=8,
    ),
    # 88 — wumpus
    MonsterEntry(
        name="wumpus", symbol=MonsterSymbol.S_QUADRUPED,
        level=8, move_speed=3, ac=2, mr=10, alignment=0,
        generation_mask=G_GENO | 1,
        attacks=(
            (AttackType.AT_BITE, DamageType.AD_PHYS, 3, 6),
        ),
        weight=2500, nutrition=500, sound=MS_BURBLE, size=MZ_LARGE,
        resists_mask=0, conveys_mask=0,
        flags1=M1_CLING | M1_ANIMAL | M1_NOHANDS | M1_OMNIVORE,
        flags2=M2_HOSTILE | M2_STRONG,
        flags3=M3_INFRAVISIBLE,
        color=CLR_CYAN,
        difficulty=9,
    ),
    # 89 — titanothere
    MonsterEntry(
        name="titanothere", symbol=MonsterSymbol.S_QUADRUPED,
        level=12, move_speed=12, ac=6, mr=0, alignment=0,
        generation_mask=G_GENO | 2,
        attacks=(
            (AttackType.AT_CLAW, DamageType.AD_PHYS, 2, 8),
        ),
        weight=2650, nutrition=650, sound=MS_SILENT, size=MZ_LARGE,
        resists_mask=0, conveys_mask=0,
        flags1=M1_ANIMAL | M1_THICK_HIDE | M1_NOHANDS | M1_HERBIVORE,
        flags2=M2_HOSTILE | M2_STRONG,
        flags3=M3_INFRAVISIBLE,
        color=CLR_GRAY,
        difficulty=13,
    ),
    # 90 — baluchitherium
    MonsterEntry(
        name="baluchitherium", symbol=MonsterSymbol.S_QUADRUPED,
        level=14, move_speed=12, ac=5, mr=0, alignment=0,
        generation_mask=G_GENO | 2,
        attacks=(
            (AttackType.AT_CLAW, DamageType.AD_PHYS, 5, 4),
            (AttackType.AT_CLAW, DamageType.AD_PHYS, 5, 4),
        ),
        weight=3800, nutrition=800, sound=MS_SILENT, size=MZ_LARGE,
        resists_mask=0, conveys_mask=0,
        flags1=M1_ANIMAL | M1_THICK_HIDE | M1_NOHANDS | M1_HERBIVORE,
        flags2=M2_HOSTILE | M2_STRONG,
        flags3=M3_INFRAVISIBLE,
        color=CLR_GRAY,
        difficulty=15,
    ),
    # 91 — mastodon
    MonsterEntry(
        name="mastodon", symbol=MonsterSymbol.S_QUADRUPED,
        level=20, move_speed=12, ac=5, mr=0, alignment=0,
        generation_mask=G_GENO | 1,
        attacks=(
            (AttackType.AT_BUTT, DamageType.AD_PHYS, 4, 8),
            (AttackType.AT_BUTT, DamageType.AD_PHYS, 4, 8),
        ),
        weight=3800, nutrition=800, sound=MS_SILENT, size=MZ_LARGE,
        resists_mask=0, conveys_mask=0,
        flags1=M1_ANIMAL | M1_THICK_HIDE | M1_NOHANDS | M1_HERBIVORE,
        flags2=M2_HOSTILE | M2_STRONG,
        flags3=M3_INFRAVISIBLE,
        color=CLR_BLACK,
        difficulty=22,
    ),
    # 92 — sewer rat
    MonsterEntry(
        name="sewer rat", symbol=MonsterSymbol.S_RODENT,
        level=0, move_speed=12, ac=7, mr=0, alignment=0,
        generation_mask=G_GENO | G_SGROUP | 1,
        attacks=(
            (AttackType.AT_BITE, DamageType.AD_PHYS, 1, 3),
        ),
        weight=20, nutrition=12, sound=MS_SQEEK, size=MZ_TINY,
        resists_mask=0, conveys_mask=0,
        flags1=M1_ANIMAL | M1_NOHANDS | M1_CARNIVORE,
        flags2=M2_HOSTILE,
        flags3=M3_INFRAVISIBLE,
        color=CLR_BROWN,
        difficulty=1,
    ),
    # 93 — giant rat
    MonsterEntry(
        name="giant rat", symbol=MonsterSymbol.S_RODENT,
        level=1, move_speed=10, ac=7, mr=0, alignment=0,
        generation_mask=G_GENO | G_SGROUP | 2,
        attacks=(
            (AttackType.AT_BITE, DamageType.AD_PHYS, 1, 3),
        ),
        weight=30, nutrition=30, sound=MS_SQEEK, size=MZ_TINY,
        resists_mask=0, conveys_mask=0,
        flags1=M1_ANIMAL | M1_NOHANDS | M1_CARNIVORE,
        flags2=M2_HOSTILE,
        flags3=M3_INFRAVISIBLE,
        color=CLR_BROWN,
        difficulty=2,
    ),
    # 94 — rabid rat
    MonsterEntry(
        name="rabid rat", symbol=MonsterSymbol.S_RODENT,
        level=2, move_speed=12, ac=6, mr=0, alignment=0,
        generation_mask=G_GENO | 1,
        attacks=(
            (AttackType.AT_BITE, DamageType.AD_DRCO, 2, 4),
        ),
        weight=30, nutrition=5, sound=MS_SQEEK, size=MZ_TINY,
        resists_mask=MR_POISON, conveys_mask=0,
        flags1=M1_ANIMAL | M1_NOHANDS | M1_POIS | M1_CARNIVORE,
        flags2=M2_HOSTILE,
        flags3=M3_INFRAVISIBLE,
        color=CLR_BROWN,
        difficulty=4,
    ),
    # 95 — wererat
    MonsterEntry(
        name="wererat", symbol=MonsterSymbol.S_RODENT,
        level=2, move_speed=12, ac=6, mr=10, alignment=-7,
        generation_mask=G_NOGEN | G_NOCORPSE,
        attacks=(
            (AttackType.AT_BITE, DamageType.AD_WERE, 1, 4),
        ),
        weight=40, nutrition=30, sound=MS_SQEEK, size=MZ_TINY,
        resists_mask=MR_POISON, conveys_mask=0,
        flags1=M1_NOHANDS | M1_POIS | M1_REGEN | M1_CARNIVORE,
        flags2=M2_NOPOLY | M2_WERE | M2_HOSTILE,
        flags3=M3_INFRAVISIBLE,
        color=CLR_BROWN,
        difficulty=3,
    ),
    # 96 — rock mole
    MonsterEntry(
        name="rock mole", symbol=MonsterSymbol.S_RODENT,
        level=3, move_speed=3, ac=0, mr=20, alignment=0,
        generation_mask=G_GENO | 2,
        attacks=(
            (AttackType.AT_BITE, DamageType.AD_PHYS, 1, 6),
        ),
        weight=30, nutrition=30, sound=MS_SILENT, size=MZ_SMALL,
        resists_mask=0, conveys_mask=0,
        flags1=M1_TUNNEL | M1_ANIMAL | M1_NOHANDS | M1_METALLIVORE,
        flags2=M2_HOSTILE | M2_GREEDY | M2_JEWELS | M2_COLLECT,
        flags3=M3_INFRAVISIBLE,
        color=CLR_GRAY,
        difficulty=4,
    ),
    # 97 — woodchuck
    MonsterEntry(
        name="woodchuck", symbol=MonsterSymbol.S_RODENT,
        level=3, move_speed=3, ac=0, mr=20, alignment=0,
        generation_mask=G_NOGEN | G_GENO,
        attacks=(
            (AttackType.AT_BITE, DamageType.AD_PHYS, 1, 6),
        ),
        weight=30, nutrition=30, sound=MS_SILENT, size=MZ_SMALL,
        resists_mask=0, conveys_mask=0,
        flags1=M1_TUNNEL | M1_ANIMAL | M1_NOHANDS | M1_SWIM | M1_HERBIVORE,
        flags2=M2_WANDER | M2_HOSTILE,
        flags3=M3_INFRAVISIBLE,
        color=CLR_BROWN,
        difficulty=4,
    ),
    # 98 — cave spider
    MonsterEntry(
        name="cave spider", symbol=MonsterSymbol.S_SPIDER,
        level=1, move_speed=12, ac=3, mr=0, alignment=0,
        generation_mask=G_GENO | G_SGROUP | 2,
        attacks=(
            (AttackType.AT_BITE, DamageType.AD_PHYS, 1, 2),
        ),
        weight=50, nutrition=50, sound=MS_SILENT, size=MZ_TINY,
        resists_mask=MR_POISON, conveys_mask=MR_POISON,
        flags1=M1_CONCEAL | M1_ANIMAL | M1_NOHANDS | M1_OVIPAROUS | M1_CARNIVORE,
        flags2=M2_HOSTILE,
        flags3=0,
        color=CLR_GRAY,
        difficulty=3,
    ),
    # 99 — centipede
    MonsterEntry(
        name="centipede", symbol=MonsterSymbol.S_SPIDER,
        level=2, move_speed=4, ac=3, mr=0, alignment=0,
        generation_mask=G_GENO | 1,
        attacks=(
            (AttackType.AT_BITE, DamageType.AD_DRST, 1, 3),
        ),
        weight=50, nutrition=50, sound=MS_SILENT, size=MZ_TINY,
        resists_mask=MR_POISON, conveys_mask=MR_POISON,
        flags1=M1_CONCEAL | M1_ANIMAL | M1_NOHANDS | M1_OVIPAROUS | M1_CARNIVORE,
        flags2=M2_HOSTILE,
        flags3=0,
        color=CLR_YELLOW,
        difficulty=4,
    ),
    # 100 — giant spider
    MonsterEntry(
        name="giant spider", symbol=MonsterSymbol.S_SPIDER,
        level=5, move_speed=15, ac=4, mr=0, alignment=0,
        generation_mask=G_GENO | 1,
        attacks=(
            (AttackType.AT_BITE, DamageType.AD_DRST, 2, 4),
        ),
        weight=100, nutrition=100, sound=MS_SILENT, size=MZ_LARGE,
        resists_mask=MR_POISON, conveys_mask=MR_POISON,
        flags1=M1_ANIMAL | M1_NOHANDS | M1_OVIPAROUS | M1_POIS | M1_CARNIVORE,
        flags2=M2_HOSTILE | M2_STRONG,
        flags3=0,
        color=CLR_MAGENTA,
        difficulty=7,
    ),
    # 101 — scorpion
    MonsterEntry(
        name="scorpion", symbol=MonsterSymbol.S_SPIDER,
        level=5, move_speed=15, ac=3, mr=0, alignment=0,
        generation_mask=G_GENO | 2,
        attacks=(
            (AttackType.AT_CLAW, DamageType.AD_PHYS, 1, 2),
            (AttackType.AT_CLAW, DamageType.AD_PHYS, 1, 2),
            (AttackType.AT_STNG, DamageType.AD_DRST, 1, 4),
        ),
        weight=50, nutrition=100, sound=MS_SILENT, size=MZ_SMALL,
        resists_mask=MR_POISON, conveys_mask=MR_POISON,
        flags1=M1_CONCEAL | M1_ANIMAL | M1_NOHANDS | M1_OVIPAROUS | M1_POIS
            | M1_CARNIVORE,
        flags2=M2_HOSTILE,
        flags3=0,
        color=CLR_RED,
        difficulty=8,
    ),
    # 102 — lurker above
    MonsterEntry(
        name="lurker above", symbol=MonsterSymbol.S_TRAPPER,
        level=10, move_speed=3, ac=3, mr=0, alignment=0,
        generation_mask=G_GENO | 2,
        attacks=(
            (AttackType.AT_ENGL, DamageType.AD_DGST, 1, 8),
        ),
        weight=800, nutrition=350, sound=MS_SILENT, size=MZ_HUGE,
        resists_mask=0, conveys_mask=0,
        flags1=M1_HIDE | M1_FLY | M1_ANIMAL | M1_NOEYES | M1_NOLIMBS | M1_NOHEAD
            | M1_CARNIVORE,
        flags2=M2_HOSTILE | M2_STALK | M2_STRONG,
        flags3=0,
        color=CLR_GRAY,
        difficulty=12,
    ),
    # 103 — trapper
    MonsterEntry(
        name="trapper", symbol=MonsterSymbol.S_TRAPPER,
        level=12, move_speed=3, ac=3, mr=0, alignment=0,
        generation_mask=G_GENO | 2,
        attacks=(
            (AttackType.AT_ENGL, DamageType.AD_DGST, 1, 10),
        ),
        weight=800, nutrition=350, sound=MS_SILENT, size=MZ_HUGE,
        resists_mask=0, conveys_mask=0,
        flags1=M1_HIDE | M1_ANIMAL | M1_NOEYES | M1_NOLIMBS | M1_NOHEAD
            | M1_CARNIVORE,
        flags2=M2_HOSTILE | M2_STALK | M2_STRONG,
        flags3=0,
        color=CLR_GREEN,
        difficulty=14,
    ),
    # 104 — pony
    MonsterEntry(
        name="pony", symbol=MonsterSymbol.S_UNICORN,
        level=3, move_speed=16, ac=6, mr=0, alignment=0,
        generation_mask=G_GENO | 2,
        attacks=(
            (AttackType.AT_KICK, DamageType.AD_PHYS, 1, 6),
            (AttackType.AT_BITE, DamageType.AD_PHYS, 1, 2),
        ),
        weight=1300, nutrition=250, sound=MS_NEIGH, size=MZ_MEDIUM,
        resists_mask=0, conveys_mask=0,
        flags1=M1_ANIMAL | M1_NOHANDS | M1_HERBIVORE,
        flags2=M2_WANDER | M2_STRONG | M2_DOMESTIC,
        flags3=M3_INFRAVISIBLE,
        color=CLR_BROWN,
        difficulty=4,
    ),
    # 105 — white unicorn
    MonsterEntry(
        name="white unicorn", symbol=MonsterSymbol.S_UNICORN,
        level=4, move_speed=24, ac=2, mr=70, alignment=7,
        generation_mask=G_GENO | 2,
        attacks=(
            (AttackType.AT_BUTT, DamageType.AD_PHYS, 1, 12),
            (AttackType.AT_KICK, DamageType.AD_PHYS, 1, 6),
        ),
        weight=1300, nutrition=300, sound=MS_NEIGH, size=MZ_LARGE,
        resists_mask=MR_POISON, conveys_mask=MR_POISON,
        flags1=M1_NOHANDS | M1_HERBIVORE,
        flags2=M2_WANDER | M2_STRONG | M2_JEWELS,
        flags3=M3_INFRAVISIBLE,
        color=CLR_WHITE,
        difficulty=6,
    ),
    # 106 — gray unicorn
    MonsterEntry(
        name="gray unicorn", symbol=MonsterSymbol.S_UNICORN,
        level=4, move_speed=24, ac=2, mr=70, alignment=0,
        generation_mask=G_GENO | 1,
        attacks=(
            (AttackType.AT_BUTT, DamageType.AD_PHYS, 1, 12),
            (AttackType.AT_KICK, DamageType.AD_PHYS, 1, 6),
        ),
        weight=1300, nutrition=300, sound=MS_NEIGH, size=MZ_LARGE,
        resists_mask=MR_POISON, conveys_mask=MR_POISON,
        flags1=M1_NOHANDS | M1_HERBIVORE,
        flags2=M2_WANDER | M2_STRONG | M2_JEWELS,
        flags3=M3_INFRAVISIBLE,
        color=CLR_GRAY,
        difficulty=6,
    ),
    # 107 — black unicorn
    MonsterEntry(
        name="black unicorn", symbol=MonsterSymbol.S_UNICORN,
        level=4, move_speed=24, ac=2, mr=70, alignment=-7,
        generation_mask=G_GENO | 1,
        attacks=(
            (AttackType.AT_BUTT, DamageType.AD_PHYS, 1, 12),
            (AttackType.AT_KICK, DamageType.AD_PHYS, 1, 6),
        ),
        weight=1300, nutrition=300, sound=MS_NEIGH, size=MZ_LARGE,
        resists_mask=MR_POISON, conveys_mask=MR_POISON,
        flags1=M1_NOHANDS | M1_HERBIVORE,
        flags2=M2_WANDER | M2_STRONG | M2_JEWELS,
        flags3=M3_INFRAVISIBLE,
        color=CLR_BLACK,
        difficulty=6,
    ),
    # 108 — horse
    MonsterEntry(
        name="horse", symbol=MonsterSymbol.S_UNICORN,
        level=5, move_speed=20, ac=5, mr=0, alignment=0,
        generation_mask=G_GENO | 2,
        attacks=(
            (AttackType.AT_KICK, DamageType.AD_PHYS, 1, 8),
            (AttackType.AT_BITE, DamageType.AD_PHYS, 1, 3),
        ),
        weight=1500, nutrition=300, sound=MS_NEIGH, size=MZ_LARGE,
        resists_mask=0, conveys_mask=0,
        flags1=M1_ANIMAL | M1_NOHANDS | M1_HERBIVORE,
        flags2=M2_WANDER | M2_STRONG | M2_DOMESTIC,
        flags3=M3_INFRAVISIBLE,
        color=CLR_BROWN,
        difficulty=7,
    ),
    # 109 — warhorse
    MonsterEntry(
        name="warhorse", symbol=MonsterSymbol.S_UNICORN,
        level=7, move_speed=24, ac=4, mr=0, alignment=0,
        generation_mask=G_GENO | 2,
        attacks=(
            (AttackType.AT_KICK, DamageType.AD_PHYS, 1, 10),
            (AttackType.AT_BITE, DamageType.AD_PHYS, 1, 4),
        ),
        weight=1800, nutrition=350, sound=MS_NEIGH, size=MZ_LARGE,
        resists_mask=0, conveys_mask=0,
        flags1=M1_ANIMAL | M1_NOHANDS | M1_HERBIVORE,
        flags2=M2_WANDER | M2_STRONG | M2_DOMESTIC,
        flags3=M3_INFRAVISIBLE,
        color=CLR_BROWN,
        difficulty=9,
    ),
    # 110 — fog cloud
    MonsterEntry(
        name="fog cloud", symbol=MonsterSymbol.S_VORTEX,
        level=3, move_speed=1, ac=0, mr=0, alignment=0,
        generation_mask=G_GENO | G_NOCORPSE | 2,
        attacks=(
            (AttackType.AT_ENGL, DamageType.AD_PHYS, 1, 6),
        ),
        weight=WT_ETHEREAL, nutrition=0, sound=MS_SILENT, size=MZ_HUGE,
        resists_mask=MR_SLEEP | MR_POISON | MR_STONE, conveys_mask=0,
        flags1=M1_FLY | M1_BREATHLESS | M1_NOEYES | M1_NOLIMBS | M1_NOHEAD
            | M1_MINDLESS | M1_AMORPHOUS | M1_UNSOLID,
        flags2=M2_HOSTILE | M2_NEUTER,
        flags3=0,
        color=CLR_GRAY,
        difficulty=4,
    ),
    # 111 — dust vortex
    MonsterEntry(
        name="dust vortex", symbol=MonsterSymbol.S_VORTEX,
        level=4, move_speed=20, ac=2, mr=30, alignment=0,
        generation_mask=G_GENO | G_NOCORPSE | 2,
        attacks=(
            (AttackType.AT_ENGL, DamageType.AD_BLND, 2, 8),
        ),
        weight=WT_ETHEREAL, nutrition=0, sound=MS_SILENT, size=MZ_HUGE,
        resists_mask=MR_SLEEP | MR_POISON | MR_STONE, conveys_mask=0,
        flags1=M1_FLY | M1_BREATHLESS | M1_NOEYES | M1_NOLIMBS | M1_NOHEAD
            | M1_MINDLESS,
        flags2=M2_HOSTILE | M2_NEUTER,
        flags3=0,
        color=CLR_BROWN,
        difficulty=6,
    ),
    # 112 — ice vortex
    MonsterEntry(
        name="ice vortex", symbol=MonsterSymbol.S_VORTEX,
        level=5, move_speed=20, ac=2, mr=30, alignment=0,
        generation_mask=G_NOHELL | G_GENO | G_NOCORPSE | 1,
        attacks=(
            (AttackType.AT_ENGL, DamageType.AD_COLD, 1, 6),
        ),
        weight=WT_ETHEREAL, nutrition=0, sound=MS_SILENT, size=MZ_HUGE,
        resists_mask=MR_COLD | MR_SLEEP | MR_POISON | MR_STONE, conveys_mask=0,
        flags1=M1_FLY | M1_BREATHLESS | M1_NOEYES | M1_NOLIMBS | M1_NOHEAD
            | M1_MINDLESS,
        flags2=M2_HOSTILE | M2_NEUTER,
        flags3=M3_INFRAVISIBLE,
        color=CLR_CYAN,
        difficulty=7,
    ),
    # 113 — energy vortex
    MonsterEntry(
        name="energy vortex", symbol=MonsterSymbol.S_VORTEX,
        level=6, move_speed=20, ac=2, mr=30, alignment=0,
        generation_mask=G_GENO | G_NOCORPSE | 1,
        attacks=(
            (AttackType.AT_ENGL, DamageType.AD_ELEC, 1, 6),
            (AttackType.AT_ENGL, DamageType.AD_DREN, 2, 6),
            (AttackType.AT_NONE, DamageType.AD_ELEC, 0, 4),
        ),
        weight=WT_ETHEREAL, nutrition=0, sound=MS_SILENT, size=MZ_HUGE,
        resists_mask=MR_ELEC | MR_SLEEP | MR_DISINT | MR_POISON | MR_STONE,
        conveys_mask=0,
        flags1=M1_FLY | M1_BREATHLESS | M1_NOEYES | M1_NOLIMBS | M1_NOHEAD
            | M1_MINDLESS | M1_UNSOLID,
        flags2=M2_HOSTILE | M2_NEUTER,
        flags3=0,
        color=HI_ZAP,
        difficulty=9,
    ),
    # 114 — steam vortex
    MonsterEntry(
        name="steam vortex", symbol=MonsterSymbol.S_VORTEX,
        level=7, move_speed=22, ac=2, mr=30, alignment=0,
        generation_mask=G_HELL | G_GENO | G_NOCORPSE | 2,
        attacks=(
            (AttackType.AT_ENGL, DamageType.AD_FIRE, 1, 8),
        ),
        weight=WT_ETHEREAL, nutrition=0, sound=MS_SILENT, size=MZ_HUGE,
        resists_mask=MR_FIRE | MR_SLEEP | MR_POISON | MR_STONE, conveys_mask=0,
        flags1=M1_FLY | M1_BREATHLESS | M1_NOEYES | M1_NOLIMBS | M1_NOHEAD
            | M1_MINDLESS | M1_UNSOLID,
        flags2=M2_HOSTILE | M2_NEUTER,
        flags3=M3_INFRAVISIBLE,
        color=CLR_BLUE,
        difficulty=9,
    ),
    # 115 — fire vortex
    MonsterEntry(
        name="fire vortex", symbol=MonsterSymbol.S_VORTEX,
        level=8, move_speed=22, ac=2, mr=30, alignment=0,
        generation_mask=G_HELL | G_GENO | G_NOCORPSE | 1,
        attacks=(
            (AttackType.AT_ENGL, DamageType.AD_FIRE, 1, 10),
            (AttackType.AT_NONE, DamageType.AD_FIRE, 0, 4),
        ),
        weight=WT_ETHEREAL, nutrition=0, sound=MS_SILENT, size=MZ_HUGE,
        resists_mask=MR_FIRE | MR_SLEEP | MR_POISON | MR_STONE, conveys_mask=0,
        flags1=M1_FLY | M1_BREATHLESS | M1_NOEYES | M1_NOLIMBS | M1_NOHEAD
            | M1_MINDLESS | M1_UNSOLID,
        flags2=M2_HOSTILE | M2_NEUTER,
        flags3=M3_INFRAVISIBLE,
        color=CLR_YELLOW,
        difficulty=10,
    ),
    # 116 — baby long worm
    MonsterEntry(
        name="baby long worm", symbol=MonsterSymbol.S_WORM,
        level=5, move_speed=3, ac=5, mr=0, alignment=0,
        generation_mask=G_GENO,
        attacks=(
            (AttackType.AT_BITE, DamageType.AD_PHYS, 1, 4),
        ),
        weight=600, nutrition=250, sound=MS_SILENT, size=MZ_LARGE,
        resists_mask=0, conveys_mask=0,
        flags1=M1_ANIMAL | M1_SLITHY | M1_NOLIMBS | M1_CARNIVORE | M1_NOTAKE,
        flags2=M2_HOSTILE,
        flags3=0,
        color=CLR_BROWN,
        difficulty=6,
    ),
    # 117 — baby purple worm
    MonsterEntry(
        name="baby purple worm", symbol=MonsterSymbol.S_WORM,
        level=8, move_speed=3, ac=5, mr=0, alignment=0,
        generation_mask=G_GENO,
        attacks=(
            (AttackType.AT_BITE, DamageType.AD_PHYS, 1, 6),
        ),
        weight=600, nutrition=250, sound=MS_SILENT, size=MZ_LARGE,
        resists_mask=0, conveys_mask=0,
        flags1=M1_ANIMAL | M1_SLITHY | M1_NOLIMBS | M1_CARNIVORE,
        flags2=M2_HOSTILE,
        flags3=0,
        color=CLR_MAGENTA,
        difficulty=9,
    ),
    # 118 — long worm
    MonsterEntry(
        name="long worm", symbol=MonsterSymbol.S_WORM,
        level=9, move_speed=3, ac=5, mr=10, alignment=0,
        generation_mask=G_GENO | 2,
        attacks=(
            (AttackType.AT_BITE, DamageType.AD_PHYS, 2, 4),
        ),
        weight=1500, nutrition=500, sound=MS_SILENT, size=MZ_GIGANTIC,
        resists_mask=0, conveys_mask=0,
        flags1=M1_ANIMAL | M1_SLITHY | M1_NOLIMBS | M1_OVIPAROUS | M1_CARNIVORE
            | M1_NOTAKE,
        flags2=M2_HOSTILE | M2_STRONG | M2_NASTY,
        flags3=0,
        color=CLR_BROWN,
        difficulty=10,
    ),
    # 119 — purple worm
    MonsterEntry(
        name="purple worm", symbol=MonsterSymbol.S_WORM,
        level=15, move_speed=9, ac=6, mr=20, alignment=0,
        generation_mask=G_GENO | 2,
        attacks=(
            (AttackType.AT_BITE, DamageType.AD_PHYS, 2, 8),
            (AttackType.AT_ENGL, DamageType.AD_DGST, 1, 10),
        ),
        weight=2700, nutrition=700, sound=MS_SILENT, size=MZ_GIGANTIC,
        resists_mask=0, conveys_mask=0,
        flags1=M1_ANIMAL | M1_SLITHY | M1_NOLIMBS | M1_OVIPAROUS | M1_CARNIVORE,
        flags2=M2_HOSTILE | M2_STRONG | M2_NASTY,
        flags3=0,
        color=CLR_MAGENTA,
        difficulty=17,
    ),
    # 120 — grid bug
    MonsterEntry(
        name="grid bug", symbol=MonsterSymbol.S_XAN,
        level=0, move_speed=12, ac=9, mr=0, alignment=0,
        generation_mask=G_GENO | G_SGROUP | G_NOCORPSE | 3,
        attacks=(
            (AttackType.AT_BITE, DamageType.AD_ELEC, 1, 1),
        ),
        weight=15, nutrition=10, sound=MS_BUZZ, size=MZ_TINY,
        resists_mask=MR_ELEC | MR_POISON, conveys_mask=0,
        flags1=M1_ANIMAL,
        flags2=M2_HOSTILE,
        flags3=M3_INFRAVISIBLE,
        color=CLR_MAGENTA,
        difficulty=1,
    ),
    # 121 — xan
    MonsterEntry(
        name="xan", symbol=MonsterSymbol.S_XAN,
        level=7, move_speed=18, ac=-4, mr=0, alignment=0,
        generation_mask=G_GENO | 3,
        attacks=(
            (AttackType.AT_STNG, DamageType.AD_LEGS, 1, 4),
        ),
        weight=300, nutrition=300, sound=MS_BUZZ, size=MZ_TINY,
        resists_mask=MR_POISON, conveys_mask=MR_POISON,
        flags1=M1_FLY | M1_ANIMAL | M1_NOHANDS | M1_POIS,
        flags2=M2_HOSTILE,
        flags3=M3_INFRAVISIBLE,
        color=CLR_RED,
        difficulty=9,
    ),
    # 122 — yellow light
    MonsterEntry(
        name="yellow light", symbol=MonsterSymbol.S_LIGHT,
        level=3, move_speed=15, ac=0, mr=0, alignment=0,
        generation_mask=G_NOCORPSE | G_GENO | 4,
        attacks=(
            (AttackType.AT_EXPL, DamageType.AD_BLND, 10, 20),
        ),
        weight=WT_ETHEREAL, nutrition=0, sound=MS_SILENT, size=MZ_SMALL,
        resists_mask=MR_FIRE | MR_COLD | MR_ELEC | MR_DISINT | MR_SLEEP
            | MR_POISON | MR_ACID | MR_STONE,
        conveys_mask=0,
        flags1=M1_FLY | M1_BREATHLESS | M1_AMORPHOUS | M1_NOEYES | M1_NOLIMBS
            | M1_NOHEAD | M1_MINDLESS | M1_UNSOLID | M1_NOTAKE,
        flags2=M2_HOSTILE | M2_NEUTER,
        flags3=M3_INFRAVISIBLE,
        color=CLR_YELLOW,
        difficulty=5,
    ),
    # 123 — black light
    MonsterEntry(
        name="black light", symbol=MonsterSymbol.S_LIGHT,
        level=5, move_speed=15, ac=0, mr=0, alignment=0,
        generation_mask=G_NOCORPSE | G_GENO | 2,
        attacks=(
            (AttackType.AT_EXPL, DamageType.AD_HALU, 10, 12),
        ),
        weight=WT_ETHEREAL, nutrition=0, sound=MS_SILENT, size=MZ_SMALL,
        resists_mask=MR_FIRE | MR_COLD | MR_ELEC | MR_DISINT | MR_SLEEP
            | MR_POISON | MR_ACID | MR_STONE,
        conveys_mask=0,
        flags1=M1_FLY | M1_BREATHLESS | M1_AMORPHOUS | M1_NOEYES | M1_NOLIMBS
            | M1_NOHEAD | M1_MINDLESS | M1_UNSOLID | M1_SEE_INVIS | M1_NOTAKE,
        flags2=M2_HOSTILE | M2_NEUTER,
        flags3=0,
        color=CLR_BLACK,
        difficulty=7,
    ),
    # 124 — zruty
    MonsterEntry(
        name="zruty", symbol=MonsterSymbol.S_ZRUTY,
        level=9, move_speed=8, ac=3, mr=0, alignment=0,
        generation_mask=G_GENO | 2,
        attacks=(
            (AttackType.AT_CLAW, DamageType.AD_PHYS, 3, 4),
            (AttackType.AT_CLAW, DamageType.AD_PHYS, 3, 4),
            (AttackType.AT_BITE, DamageType.AD_PHYS, 3, 6),
        ),
        weight=1200, nutrition=600, sound=MS_SILENT, size=MZ_LARGE,
        resists_mask=0, conveys_mask=0,
        flags1=M1_ANIMAL | M1_HUMANOID | M1_CARNIVORE,
        flags2=M2_HOSTILE | M2_STRONG,
        flags3=M3_INFRAVISIBLE,
        color=CLR_BROWN,
        difficulty=11,
    ),
    # 125 — couatl
    MonsterEntry(
        name="couatl", symbol=MonsterSymbol.S_ANGEL,
        level=8, move_speed=10, ac=5, mr=30, alignment=7,
        generation_mask=G_NOHELL | G_SGROUP | G_NOCORPSE | 1,
        attacks=(
            (AttackType.AT_BITE, DamageType.AD_DRST, 2, 4),
            (AttackType.AT_BITE, DamageType.AD_PHYS, 1, 3),
            (AttackType.AT_HUGS, DamageType.AD_WRAP, 2, 4),
        ),
        weight=900, nutrition=400, sound=MS_HISS, size=MZ_LARGE,
        resists_mask=MR_POISON, conveys_mask=0,
        flags1=M1_FLY | M1_NOHANDS | M1_SLITHY | M1_POIS,
        flags2=M2_MINION | M2_STALK | M2_STRONG | M2_NASTY,
        flags3=M3_INFRAVISIBLE | M3_INFRAVISION,
        color=CLR_GREEN,
        difficulty=11,
    ),
    # 126 — Aleax
    MonsterEntry(
        name="Aleax", symbol=MonsterSymbol.S_ANGEL,
        level=10, move_speed=8, ac=0, mr=30, alignment=7,
        generation_mask=G_NOHELL | G_NOCORPSE | 1,
        attacks=(
            (AttackType.AT_WEAP, DamageType.AD_PHYS, 1, 6),
            (AttackType.AT_WEAP, DamageType.AD_PHYS, 1, 6),
            (AttackType.AT_KICK, DamageType.AD_PHYS, 1, 4),
        ),
        weight=WT_HUMAN, nutrition=400, sound=MS_IMITATE, size=MZ_HUMAN,
        resists_mask=MR_COLD | MR_ELEC | MR_SLEEP | MR_POISON, conveys_mask=0,
        flags1=M1_HUMANOID | M1_SEE_INVIS,
        flags2=M2_MINION | M2_STALK | M2_NASTY | M2_COLLECT,
        flags3=M3_INFRAVISIBLE | M3_INFRAVISION,
        color=CLR_YELLOW,
        difficulty=12,
    ),
    # 127 — Angel
    MonsterEntry(
        name="Angel", symbol=MonsterSymbol.S_ANGEL,
        level=14, move_speed=10, ac=-4, mr=55, alignment=12,
        generation_mask=G_NOHELL | G_NOCORPSE | 1,
        attacks=(
            (AttackType.AT_WEAP, DamageType.AD_PHYS, 1, 6),
            (AttackType.AT_WEAP, DamageType.AD_PHYS, 1, 6),
            (AttackType.AT_CLAW, DamageType.AD_PHYS, 1, 4),
            (AttackType.AT_MAGC, DamageType.AD_MAGM, 2, 6),
        ),
        weight=WT_HUMAN, nutrition=400, sound=MS_CUSS, size=MZ_HUMAN,
        resists_mask=MR_COLD | MR_ELEC | MR_SLEEP | MR_POISON, conveys_mask=0,
        flags1=M1_FLY | M1_HUMANOID | M1_SEE_INVIS,
        flags2=M2_NOPOLY | M2_MINION | M2_STALK | M2_STRONG | M2_NASTY | M2_COLLECT,
        flags3=M3_INFRAVISIBLE | M3_INFRAVISION,
        color=CLR_WHITE,
        difficulty=19,
    ),
    # 128 — ki-rin
    MonsterEntry(
        name="ki-rin", symbol=MonsterSymbol.S_ANGEL,
        level=16, move_speed=18, ac=-5, mr=90, alignment=15,
        generation_mask=G_NOHELL | G_NOCORPSE | 1,
        attacks=(
            (AttackType.AT_KICK, DamageType.AD_PHYS, 2, 4),
            (AttackType.AT_KICK, DamageType.AD_PHYS, 2, 4),
            (AttackType.AT_BUTT, DamageType.AD_PHYS, 3, 6),
            (AttackType.AT_MAGC, DamageType.AD_SPEL, 2, 6),
        ),
        weight=WT_HUMAN, nutrition=400, sound=MS_NEIGH, size=MZ_LARGE,
        resists_mask=0, conveys_mask=0,
        flags1=M1_FLY | M1_ANIMAL | M1_NOHANDS | M1_SEE_INVIS,
        flags2=M2_NOPOLY | M2_MINION | M2_STALK | M2_STRONG | M2_NASTY | M2_LORD,
        flags3=M3_INFRAVISIBLE | M3_INFRAVISION,
        color=HI_GOLD,
        difficulty=21,
    ),
    # 129 — Archon
    MonsterEntry(
        name="Archon", symbol=MonsterSymbol.S_ANGEL,
        level=19, move_speed=16, ac=-6, mr=80, alignment=15,
        generation_mask=G_NOHELL | G_NOCORPSE | 1,
        attacks=(
            (AttackType.AT_WEAP, DamageType.AD_PHYS, 2, 4),
            (AttackType.AT_WEAP, DamageType.AD_PHYS, 2, 4),
            (AttackType.AT_GAZE, DamageType.AD_BLND, 2, 6),
            (AttackType.AT_CLAW, DamageType.AD_PHYS, 1, 8),
            (AttackType.AT_MAGC, DamageType.AD_SPEL, 4, 6),
        ),
        weight=WT_HUMAN, nutrition=400, sound=MS_CUSS, size=MZ_LARGE,
        resists_mask=MR_FIRE | MR_COLD | MR_ELEC | MR_SLEEP | MR_POISON,
        conveys_mask=0,
        flags1=M1_FLY | M1_HUMANOID | M1_SEE_INVIS | M1_REGEN,
        flags2=M2_NOPOLY | M2_MINION | M2_STALK | M2_STRONG | M2_NASTY | M2_LORD
            | M2_COLLECT | M2_MAGIC,
        flags3=M3_INFRAVISIBLE | M3_INFRAVISION,
        color=HI_LORD,
        difficulty=26,
    ),
    # 130 — bat
    MonsterEntry(
        name="bat", symbol=MonsterSymbol.S_BAT,
        level=0, move_speed=22, ac=8, mr=0, alignment=0,
        generation_mask=G_GENO | G_SGROUP | 1,
        attacks=(
            (AttackType.AT_BITE, DamageType.AD_PHYS, 1, 4),
        ),
        weight=20, nutrition=20, sound=MS_SQEEK, size=MZ_TINY,
        resists_mask=0, conveys_mask=0,
        flags1=M1_FLY | M1_ANIMAL | M1_NOHANDS | M1_CARNIVORE,
        flags2=M2_WANDER,
        flags3=M3_INFRAVISIBLE,
        color=CLR_BROWN,
        difficulty=2,
    ),
)
