"""Monster entries chunk 1 — vendor/nethack/include/monsters.h lines 89-648."""
from Nethax.nethax.constants.monsters import (
    MonsterEntry,
    MonsterSymbol,
    AttackType, DamageType,
    # generation mask bits
    G_GENO, G_NOGEN, G_NOHELL, G_HELL, G_NOCORPSE, G_SGROUP, G_LGROUP, G_UNIQ,
    # resist/convey bits
    MR_FIRE, MR_COLD, MR_SLEEP, MR_ELEC, MR_POISON, MR_ACID, MR_STONE,
    # M1 flags
    M1_FLY, M1_SWIM, M1_AMORPHOUS, M1_BREATHLESS, M1_NOTAKE,
    M1_NOEYES, M1_NOHANDS, M1_NOLIMBS, M1_NOHEAD, M1_MINDLESS,
    M1_HUMANOID, M1_ANIMAL, M1_THICK_HIDE, M1_HIDE, M1_OVIPAROUS, M1_REGEN,
    M1_SEE_INVIS, M1_TPORT, M1_TPORT_CNTRL, M1_ACID, M1_POIS,
    M1_CARNIVORE, M1_OMNIVORE, M1_TUNNEL, M1_NEEDPICK, M1_AMPHIBIOUS,
    # M2 flags
    M2_HOSTILE, M2_PEACEFUL, M2_DOMESTIC, M2_WANDER, M2_STALK,
    M2_NOPOLY, M2_WERE, M2_FEMALE, M2_NEUTER, M2_MALE, M2_PNAME,
    M2_PRINCE, M2_LORD, M2_STRONG, M2_NASTY, M2_MAGIC,
    M2_DWARF, M2_GREEDY, M2_JEWELS, M2_COLLECT,
    # M3 flags
    M3_INFRAVISIBLE, M3_INFRAVISION, M3_DISPLACES,
    # sound constants
    MS_SILENT, MS_BARK, MS_MEW, MS_GROWL, MS_HISS, MS_BUZZ,
    MS_GRUNT, MS_LAUGH, MS_HUMANOID, MS_ORC, MS_SQAWK, MS_CUSS,
    # size constants
    MZ_TINY, MZ_SMALL, MZ_MEDIUM, MZ_LARGE, MZ_HUMAN,
    # color constants
    CLR_BLACK, CLR_RED, CLR_GREEN, CLR_BROWN, CLR_BLUE,
    CLR_CYAN, CLR_GRAY, CLR_YELLOW, CLR_WHITE,
    CLR_MAGENTA, CLR_BRIGHT_MAGENTA, CLR_BRIGHT_BLUE,
    HI_LORD, HI_DOMESTIC, HI_ZAP,
    # weight constants
    WT_JELLY,
)

ENTRIES = (
    # 0 — giant ant  (line 89)
    MonsterEntry(
        name="giant ant",
        symbol=MonsterSymbol.S_ANT,
        level=2, move_speed=18, ac=3, mr=0, alignment=0,
        generation_mask=G_GENO | G_SGROUP | 3,
        attacks=(
            (AttackType.AT_BITE, DamageType.AD_PHYS, 1, 4),
        ),
        weight=10, nutrition=10,
        sound=MS_SILENT, size=MZ_TINY,
        resists_mask=0, conveys_mask=0,
        flags1=M1_ANIMAL | M1_NOHANDS | M1_OVIPAROUS | M1_CARNIVORE,
        flags2=M2_HOSTILE, flags3=0,
        color=CLR_BROWN,
        difficulty=4,
    ),
    # 1 — killer bee  (line 96)
    MonsterEntry(
        name="killer bee",
        symbol=MonsterSymbol.S_ANT,
        level=1, move_speed=18, ac=-1, mr=0, alignment=0,
        generation_mask=G_GENO | G_LGROUP | 2,
        attacks=(
            (AttackType.AT_STNG, DamageType.AD_DRST, 1, 3),
        ),
        weight=1, nutrition=5,
        sound=MS_BUZZ, size=MZ_TINY,
        resists_mask=MR_POISON, conveys_mask=MR_POISON,
        flags1=M1_ANIMAL | M1_FLY | M1_NOHANDS | M1_POIS,
        flags2=M2_HOSTILE | M2_FEMALE, flags3=0,
        color=CLR_YELLOW,
        difficulty=5,
    ),
    # 2 — soldier ant  (line 103)
    MonsterEntry(
        name="soldier ant",
        symbol=MonsterSymbol.S_ANT,
        level=3, move_speed=18, ac=3, mr=0, alignment=0,
        generation_mask=G_GENO | G_SGROUP | 2,
        attacks=(
            (AttackType.AT_BITE, DamageType.AD_PHYS, 2, 4),
            (AttackType.AT_STNG, DamageType.AD_DRST, 3, 4),
        ),
        weight=20, nutrition=5,
        sound=MS_SILENT, size=MZ_TINY,
        resists_mask=MR_POISON, conveys_mask=MR_POISON,
        flags1=M1_ANIMAL | M1_NOHANDS | M1_OVIPAROUS | M1_POIS | M1_CARNIVORE,
        flags2=M2_HOSTILE, flags3=0,
        color=CLR_BLUE,
        difficulty=6,
    ),
    # 3 — fire ant  (line 111)
    MonsterEntry(
        name="fire ant",
        symbol=MonsterSymbol.S_ANT,
        level=3, move_speed=18, ac=3, mr=10, alignment=0,
        generation_mask=G_GENO | G_SGROUP | 1,
        attacks=(
            (AttackType.AT_BITE, DamageType.AD_PHYS, 2, 4),
            (AttackType.AT_BITE, DamageType.AD_FIRE, 2, 4),
        ),
        weight=30, nutrition=10,
        sound=MS_SILENT, size=MZ_TINY,
        resists_mask=MR_FIRE, conveys_mask=MR_FIRE,
        flags1=M1_ANIMAL | M1_NOHANDS | M1_OVIPAROUS | M1_CARNIVORE,
        flags2=M2_HOSTILE, flags3=M3_INFRAVISIBLE,
        color=CLR_RED,
        difficulty=6,
    ),
    # 4 — giant beetle  (line 119)
    MonsterEntry(
        name="giant beetle",
        symbol=MonsterSymbol.S_ANT,
        level=5, move_speed=6, ac=4, mr=0, alignment=0,
        generation_mask=G_GENO | 3,
        attacks=(
            (AttackType.AT_BITE, DamageType.AD_PHYS, 3, 6),
        ),
        weight=10, nutrition=10,
        sound=MS_SILENT, size=MZ_LARGE,
        resists_mask=MR_POISON, conveys_mask=MR_POISON,
        flags1=M1_ANIMAL | M1_NOHANDS | M1_POIS | M1_CARNIVORE,
        flags2=M2_HOSTILE, flags3=0,
        color=CLR_BLACK,
        difficulty=6,
    ),
    # 5 — queen bee  (line 126)
    MonsterEntry(
        name="queen bee",
        symbol=MonsterSymbol.S_ANT,
        level=9, move_speed=24, ac=-4, mr=0, alignment=0,
        generation_mask=G_GENO | G_NOGEN,
        attacks=(
            (AttackType.AT_STNG, DamageType.AD_DRST, 1, 8),
        ),
        weight=1, nutrition=5,
        sound=MS_BUZZ, size=MZ_TINY,
        resists_mask=MR_POISON, conveys_mask=MR_POISON,
        flags1=M1_ANIMAL | M1_FLY | M1_NOHANDS | M1_OVIPAROUS | M1_POIS,
        flags2=M2_HOSTILE | M2_FEMALE | M2_PRINCE, flags3=0,
        color=HI_LORD,
        difficulty=12,
    ),
    # 6 — acid blob  (line 137)
    MonsterEntry(
        name="acid blob",
        symbol=MonsterSymbol.S_BLOB,
        level=1, move_speed=3, ac=8, mr=0, alignment=0,
        generation_mask=G_GENO | 2,
        attacks=(
            (AttackType.AT_NONE, DamageType.AD_ACID, 1, 8),
        ),
        weight=30, nutrition=10,
        sound=MS_SILENT, size=MZ_TINY,
        resists_mask=MR_SLEEP | MR_POISON | MR_ACID | MR_STONE,
        conveys_mask=MR_STONE,
        flags1=M1_BREATHLESS | M1_AMORPHOUS | M1_NOEYES | M1_NOLIMBS | M1_NOHEAD | M1_MINDLESS | M1_ACID,
        flags2=M2_WANDER | M2_NEUTER, flags3=0,
        color=CLR_GREEN,
        difficulty=2,
    ),
    # 7 — quivering blob  (line 147)
    MonsterEntry(
        name="quivering blob",
        symbol=MonsterSymbol.S_BLOB,
        level=5, move_speed=1, ac=8, mr=0, alignment=0,
        generation_mask=G_GENO | 2,
        attacks=(
            (AttackType.AT_TUCH, DamageType.AD_PHYS, 1, 8),
        ),
        weight=200, nutrition=100,
        sound=MS_SILENT, size=MZ_SMALL,
        resists_mask=MR_SLEEP | MR_POISON, conveys_mask=MR_POISON,
        flags1=M1_NOEYES | M1_NOLIMBS | M1_NOHEAD | M1_MINDLESS,
        flags2=M2_WANDER | M2_HOSTILE | M2_NEUTER, flags3=0,
        color=CLR_WHITE,
        difficulty=6,
    ),
    # 8 — gelatinous cube  (line 155)
    MonsterEntry(
        name="gelatinous cube",
        symbol=MonsterSymbol.S_BLOB,
        level=6, move_speed=6, ac=8, mr=0, alignment=0,
        generation_mask=G_GENO | 2,
        attacks=(
            (AttackType.AT_TUCH, DamageType.AD_PLYS, 2, 4),
            (AttackType.AT_NONE, DamageType.AD_PLYS, 1, 4),
        ),
        weight=600, nutrition=150,
        sound=MS_SILENT, size=MZ_LARGE,
        resists_mask=MR_FIRE | MR_COLD | MR_ELEC | MR_SLEEP | MR_POISON | MR_ACID | MR_STONE,
        conveys_mask=MR_FIRE | MR_COLD | MR_ELEC | MR_SLEEP,
        flags1=M1_NOEYES | M1_NOLIMBS | M1_NOHEAD | M1_MINDLESS | M1_OMNIVORE | M1_ACID,
        flags2=M2_WANDER | M2_HOSTILE | M2_NEUTER, flags3=0,
        color=CLR_CYAN,
        difficulty=8,
    ),
    # 9 — chickatrice  (line 170)
    MonsterEntry(
        name="chickatrice",
        symbol=MonsterSymbol.S_COCKATRICE,
        level=4, move_speed=4, ac=8, mr=30, alignment=0,
        generation_mask=G_GENO | G_SGROUP | 1,
        attacks=(
            (AttackType.AT_BITE, DamageType.AD_PHYS, 1, 2),
            (AttackType.AT_TUCH, DamageType.AD_STON, 0, 0),
            (AttackType.AT_NONE, DamageType.AD_STON, 0, 0),
        ),
        weight=10, nutrition=10,
        sound=MS_HISS, size=MZ_TINY,
        resists_mask=MR_POISON | MR_STONE, conveys_mask=MR_POISON | MR_STONE,
        flags1=M1_ANIMAL | M1_NOHANDS | M1_OMNIVORE,
        flags2=M2_HOSTILE, flags3=M3_INFRAVISIBLE,
        color=CLR_BROWN,
        difficulty=7,
    ),
    # 10 — cockatrice  (line 178)
    MonsterEntry(
        name="cockatrice",
        symbol=MonsterSymbol.S_COCKATRICE,
        level=5, move_speed=6, ac=6, mr=30, alignment=0,
        generation_mask=G_GENO | 5,
        attacks=(
            (AttackType.AT_BITE, DamageType.AD_PHYS, 1, 3),
            (AttackType.AT_TUCH, DamageType.AD_STON, 0, 0),
            (AttackType.AT_NONE, DamageType.AD_STON, 0, 0),
        ),
        weight=30, nutrition=30,
        sound=MS_HISS, size=MZ_SMALL,
        resists_mask=MR_POISON | MR_STONE, conveys_mask=MR_POISON | MR_STONE,
        flags1=M1_ANIMAL | M1_NOHANDS | M1_OMNIVORE | M1_OVIPAROUS,
        flags2=M2_HOSTILE, flags3=M3_INFRAVISIBLE,
        color=CLR_YELLOW,
        difficulty=8,
    ),
    # 11 — pyrolisk  (line 187)
    MonsterEntry(
        name="pyrolisk",
        symbol=MonsterSymbol.S_COCKATRICE,
        level=6, move_speed=6, ac=6, mr=30, alignment=0,
        generation_mask=G_GENO | 1,
        attacks=(
            (AttackType.AT_GAZE, DamageType.AD_FIRE, 2, 6),
        ),
        weight=30, nutrition=30,
        sound=MS_HISS, size=MZ_SMALL,
        resists_mask=MR_POISON | MR_FIRE, conveys_mask=MR_POISON | MR_FIRE,
        flags1=M1_ANIMAL | M1_NOHANDS | M1_OMNIVORE | M1_OVIPAROUS,
        flags2=M2_HOSTILE, flags3=M3_INFRAVISIBLE,
        color=CLR_RED,
        difficulty=8,
    ),
    # 12 — jackal  (line 199)
    MonsterEntry(
        name="jackal",
        symbol=MonsterSymbol.S_DOG,
        level=0, move_speed=12, ac=7, mr=0, alignment=0,
        generation_mask=G_GENO | G_SGROUP | 3,
        attacks=(
            (AttackType.AT_BITE, DamageType.AD_PHYS, 1, 2),
        ),
        weight=300, nutrition=250,
        sound=MS_BARK, size=MZ_SMALL,
        resists_mask=0, conveys_mask=0,
        flags1=M1_ANIMAL | M1_NOHANDS | M1_CARNIVORE,
        flags2=M2_HOSTILE, flags3=M3_INFRAVISIBLE,
        color=CLR_BROWN,
        difficulty=1,
    ),
    # 13 — fox  (line 206)
    MonsterEntry(
        name="fox",
        symbol=MonsterSymbol.S_DOG,
        level=0, move_speed=15, ac=7, mr=0, alignment=0,
        generation_mask=G_GENO | 1,
        attacks=(
            (AttackType.AT_BITE, DamageType.AD_PHYS, 1, 3),
        ),
        weight=300, nutrition=250,
        sound=MS_BARK, size=MZ_SMALL,
        resists_mask=0, conveys_mask=0,
        flags1=M1_ANIMAL | M1_NOHANDS | M1_CARNIVORE,
        flags2=M2_HOSTILE, flags3=M3_INFRAVISIBLE,
        color=CLR_RED,
        difficulty=1,
    ),
    # 14 — coyote  (line 213)
    MonsterEntry(
        name="coyote",
        symbol=MonsterSymbol.S_DOG,
        level=1, move_speed=12, ac=7, mr=0, alignment=0,
        generation_mask=G_GENO | G_SGROUP | 1,
        attacks=(
            (AttackType.AT_BITE, DamageType.AD_PHYS, 1, 4),
        ),
        weight=300, nutrition=250,
        sound=MS_BARK, size=MZ_SMALL,
        resists_mask=0, conveys_mask=0,
        flags1=M1_ANIMAL | M1_NOHANDS | M1_CARNIVORE,
        flags2=M2_HOSTILE, flags3=M3_INFRAVISIBLE,
        color=CLR_BROWN,
        difficulty=2,
    ),
    # 15 — werejackal  (line 220)
    MonsterEntry(
        name="werejackal",
        symbol=MonsterSymbol.S_DOG,
        level=2, move_speed=12, ac=7, mr=10, alignment=-7,
        generation_mask=G_NOGEN | G_NOCORPSE,
        attacks=(
            (AttackType.AT_BITE, DamageType.AD_WERE, 1, 4),
        ),
        weight=300, nutrition=250,
        sound=MS_BARK, size=MZ_SMALL,
        resists_mask=MR_POISON, conveys_mask=0,
        flags1=M1_NOHANDS | M1_POIS | M1_REGEN | M1_CARNIVORE,
        flags2=M2_NOPOLY | M2_WERE | M2_HOSTILE, flags3=M3_INFRAVISIBLE,
        color=CLR_BROWN,
        difficulty=3,
    ),
    # 16 — little dog  (line 228)
    MonsterEntry(
        name="little dog",
        symbol=MonsterSymbol.S_DOG,
        level=2, move_speed=18, ac=6, mr=0, alignment=0,
        generation_mask=G_GENO | 1,
        attacks=(
            (AttackType.AT_BITE, DamageType.AD_PHYS, 1, 6),
        ),
        weight=150, nutrition=150,
        sound=MS_BARK, size=MZ_SMALL,
        resists_mask=0, conveys_mask=0,
        flags1=M1_ANIMAL | M1_NOHANDS | M1_CARNIVORE,
        flags2=M2_DOMESTIC, flags3=M3_INFRAVISIBLE,
        color=HI_DOMESTIC,
        difficulty=3,
    ),
    # 17 — dingo  (line 235)
    MonsterEntry(
        name="dingo",
        symbol=MonsterSymbol.S_DOG,
        level=4, move_speed=16, ac=5, mr=0, alignment=0,
        generation_mask=G_GENO | 1,
        attacks=(
            (AttackType.AT_BITE, DamageType.AD_PHYS, 1, 6),
        ),
        weight=400, nutrition=200,
        sound=MS_BARK, size=MZ_MEDIUM,
        resists_mask=0, conveys_mask=0,
        flags1=M1_ANIMAL | M1_NOHANDS | M1_CARNIVORE,
        flags2=M2_HOSTILE, flags3=M3_INFRAVISIBLE,
        color=CLR_YELLOW,
        difficulty=5,
    ),
    # 18 — dog  (line 242)
    MonsterEntry(
        name="dog",
        symbol=MonsterSymbol.S_DOG,
        level=4, move_speed=16, ac=5, mr=0, alignment=0,
        generation_mask=G_GENO | 1,
        attacks=(
            (AttackType.AT_BITE, DamageType.AD_PHYS, 1, 6),
        ),
        weight=400, nutrition=200,
        sound=MS_BARK, size=MZ_MEDIUM,
        resists_mask=0, conveys_mask=0,
        flags1=M1_ANIMAL | M1_NOHANDS | M1_CARNIVORE,
        flags2=M2_DOMESTIC, flags3=M3_INFRAVISIBLE,
        color=HI_DOMESTIC,
        difficulty=5,
    ),
    # 19 — large dog  (line 249)
    MonsterEntry(
        name="large dog",
        symbol=MonsterSymbol.S_DOG,
        level=6, move_speed=15, ac=4, mr=0, alignment=0,
        generation_mask=G_GENO | 1,
        attacks=(
            (AttackType.AT_BITE, DamageType.AD_PHYS, 2, 4),
        ),
        weight=800, nutrition=250,
        sound=MS_BARK, size=MZ_MEDIUM,
        resists_mask=0, conveys_mask=0,
        flags1=M1_ANIMAL | M1_NOHANDS | M1_CARNIVORE,
        flags2=M2_STRONG | M2_DOMESTIC, flags3=M3_INFRAVISIBLE,
        color=HI_DOMESTIC,
        difficulty=7,
    ),
    # 20 — wolf  (line 257)
    MonsterEntry(
        name="wolf",
        symbol=MonsterSymbol.S_DOG,
        level=5, move_speed=12, ac=4, mr=0, alignment=0,
        generation_mask=G_GENO | G_SGROUP | 2,
        attacks=(
            (AttackType.AT_BITE, DamageType.AD_PHYS, 2, 4),
        ),
        weight=500, nutrition=250,
        sound=MS_BARK, size=MZ_MEDIUM,
        resists_mask=0, conveys_mask=0,
        flags1=M1_ANIMAL | M1_NOHANDS | M1_CARNIVORE,
        flags2=M2_HOSTILE, flags3=M3_INFRAVISIBLE,
        color=CLR_BROWN,
        difficulty=6,
    ),
    # 21 — werewolf  (line 267)
    MonsterEntry(
        name="werewolf",
        symbol=MonsterSymbol.S_DOG,
        level=5, move_speed=12, ac=4, mr=20, alignment=-7,
        generation_mask=G_NOGEN | G_NOCORPSE,
        attacks=(
            (AttackType.AT_BITE, DamageType.AD_WERE, 2, 6),
        ),
        weight=500, nutrition=250,
        sound=MS_BARK, size=MZ_MEDIUM,
        resists_mask=MR_POISON, conveys_mask=0,
        flags1=M1_NOHANDS | M1_POIS | M1_REGEN | M1_CARNIVORE,
        flags2=M2_NOPOLY | M2_WERE | M2_HOSTILE, flags3=M3_INFRAVISIBLE,
        color=CLR_BROWN,
        difficulty=6,
    ),
    # 22 — winter wolf cub  (line 275)
    MonsterEntry(
        name="winter wolf cub",
        symbol=MonsterSymbol.S_DOG,
        level=5, move_speed=12, ac=4, mr=0, alignment=-5,
        generation_mask=G_NOHELL | G_GENO | G_SGROUP | 2,
        attacks=(
            (AttackType.AT_BITE, DamageType.AD_PHYS, 1, 8),
            (AttackType.AT_BREA, DamageType.AD_COLD, 1, 6),
        ),
        weight=250, nutrition=200,
        sound=MS_BARK, size=MZ_SMALL,
        resists_mask=MR_COLD, conveys_mask=MR_COLD,
        flags1=M1_ANIMAL | M1_NOHANDS | M1_CARNIVORE,
        flags2=M2_HOSTILE, flags3=0,
        color=CLR_CYAN,
        difficulty=7,
    ),
    # 23 — warg  (line 283)
    MonsterEntry(
        name="warg",
        symbol=MonsterSymbol.S_DOG,
        level=7, move_speed=12, ac=4, mr=0, alignment=-5,
        generation_mask=G_GENO | G_SGROUP | 2,
        attacks=(
            (AttackType.AT_BITE, DamageType.AD_PHYS, 2, 6),
        ),
        weight=850, nutrition=350,
        sound=MS_BARK, size=MZ_MEDIUM,
        resists_mask=0, conveys_mask=0,
        flags1=M1_ANIMAL | M1_NOHANDS | M1_CARNIVORE,
        flags2=M2_HOSTILE, flags3=M3_INFRAVISIBLE,
        color=CLR_BROWN,
        difficulty=8,
    ),
    # 24 — winter wolf  (line 290)
    MonsterEntry(
        name="winter wolf",
        symbol=MonsterSymbol.S_DOG,
        level=7, move_speed=12, ac=4, mr=20, alignment=0,
        generation_mask=G_NOHELL | G_GENO | 1,
        attacks=(
            (AttackType.AT_BITE, DamageType.AD_PHYS, 2, 6),
            (AttackType.AT_BREA, DamageType.AD_COLD, 2, 6),
        ),
        weight=700, nutrition=300,
        sound=MS_BARK, size=MZ_LARGE,
        resists_mask=MR_COLD, conveys_mask=MR_COLD,
        flags1=M1_ANIMAL | M1_NOHANDS | M1_CARNIVORE,
        flags2=M2_HOSTILE | M2_STRONG, flags3=0,
        color=CLR_CYAN,
        difficulty=9,
    ),
    # 25 — hell hound pup  (line 297)
    MonsterEntry(
        name="hell hound pup",
        symbol=MonsterSymbol.S_DOG,
        level=7, move_speed=12, ac=4, mr=20, alignment=-5,
        generation_mask=G_HELL | G_GENO | G_SGROUP | 1,
        attacks=(
            (AttackType.AT_BITE, DamageType.AD_PHYS, 2, 6),
            (AttackType.AT_BREA, DamageType.AD_FIRE, 2, 6),
        ),
        weight=200, nutrition=200,
        sound=MS_BARK, size=MZ_SMALL,
        resists_mask=MR_FIRE, conveys_mask=MR_FIRE,
        flags1=M1_ANIMAL | M1_NOHANDS | M1_CARNIVORE,
        flags2=M2_HOSTILE, flags3=M3_INFRAVISIBLE,
        color=CLR_RED,
        difficulty=9,
    ),
    # 26 — hell hound  (line 304)
    MonsterEntry(
        name="hell hound",
        symbol=MonsterSymbol.S_DOG,
        level=12, move_speed=14, ac=2, mr=20, alignment=0,
        generation_mask=G_HELL | G_GENO | 1,
        attacks=(
            (AttackType.AT_BITE, DamageType.AD_PHYS, 3, 6),
            (AttackType.AT_BREA, DamageType.AD_FIRE, 3, 6),
        ),
        weight=600, nutrition=300,
        sound=MS_BARK, size=MZ_MEDIUM,
        resists_mask=MR_FIRE, conveys_mask=MR_FIRE,
        flags1=M1_ANIMAL | M1_NOHANDS | M1_CARNIVORE,
        flags2=M2_HOSTILE | M2_STRONG, flags3=M3_INFRAVISIBLE,
        color=CLR_RED,
        difficulty=14,
    ),
    # 27 — gas spore  (line 325)
    MonsterEntry(
        name="gas spore",
        symbol=MonsterSymbol.S_EYE,
        level=1, move_speed=3, ac=10, mr=0, alignment=0,
        generation_mask=G_NOCORPSE | G_GENO | 1,
        attacks=(
            (AttackType.AT_BOOM, DamageType.AD_PHYS, 4, 6),
        ),
        weight=10, nutrition=10,
        sound=MS_SILENT, size=MZ_SMALL,
        resists_mask=0, conveys_mask=0,
        flags1=M1_FLY | M1_BREATHLESS | M1_NOLIMBS | M1_NOHEAD | M1_MINDLESS,
        flags2=M2_HOSTILE | M2_NEUTER, flags3=0,
        color=CLR_GRAY,
        difficulty=2,
    ),
    # 28 — floating eye  (line 333)
    MonsterEntry(
        name="floating eye",
        symbol=MonsterSymbol.S_EYE,
        level=2, move_speed=1, ac=9, mr=10, alignment=0,
        generation_mask=G_GENO | 5,
        attacks=(
            (AttackType.AT_NONE, DamageType.AD_PLYS, 0, 70),
        ),
        weight=10, nutrition=10,
        sound=MS_SILENT, size=MZ_SMALL,
        resists_mask=0, conveys_mask=0,
        flags1=M1_FLY | M1_AMPHIBIOUS | M1_NOLIMBS | M1_NOHEAD | M1_NOTAKE,
        flags2=M2_HOSTILE | M2_NEUTER, flags3=M3_INFRAVISIBLE,
        color=CLR_BLUE,
        difficulty=3,
    ),
    # 29 — freezing sphere  (line 341)
    MonsterEntry(
        name="freezing sphere",
        symbol=MonsterSymbol.S_EYE,
        level=6, move_speed=13, ac=4, mr=0, alignment=0,
        generation_mask=G_NOCORPSE | G_NOHELL | G_GENO | 2,
        attacks=(
            (AttackType.AT_EXPL, DamageType.AD_COLD, 4, 6),
        ),
        weight=10, nutrition=10,
        sound=MS_SILENT, size=MZ_SMALL,
        resists_mask=MR_COLD, conveys_mask=MR_COLD,
        flags1=M1_FLY | M1_BREATHLESS | M1_NOLIMBS | M1_NOHEAD | M1_MINDLESS | M1_NOTAKE,
        flags2=M2_HOSTILE | M2_NEUTER, flags3=M3_INFRAVISIBLE,
        color=CLR_WHITE,
        difficulty=8,
    ),
    # 30 — flaming sphere  (line 350)
    MonsterEntry(
        name="flaming sphere",
        symbol=MonsterSymbol.S_EYE,
        level=6, move_speed=13, ac=4, mr=0, alignment=0,
        generation_mask=G_NOCORPSE | G_GENO | 2,
        attacks=(
            (AttackType.AT_EXPL, DamageType.AD_FIRE, 4, 6),
        ),
        weight=10, nutrition=10,
        sound=MS_SILENT, size=MZ_SMALL,
        resists_mask=MR_FIRE, conveys_mask=MR_FIRE,
        flags1=M1_FLY | M1_BREATHLESS | M1_NOLIMBS | M1_NOHEAD | M1_MINDLESS | M1_NOTAKE,
        flags2=M2_HOSTILE | M2_NEUTER, flags3=M3_INFRAVISIBLE,
        color=CLR_RED,
        difficulty=8,
    ),
    # 31 — shocking sphere  (line 358)
    MonsterEntry(
        name="shocking sphere",
        symbol=MonsterSymbol.S_EYE,
        level=6, move_speed=13, ac=4, mr=0, alignment=0,
        generation_mask=G_NOCORPSE | G_GENO | 2,
        attacks=(
            (AttackType.AT_EXPL, DamageType.AD_ELEC, 4, 6),
        ),
        weight=10, nutrition=10,
        sound=MS_SILENT, size=MZ_SMALL,
        resists_mask=MR_ELEC, conveys_mask=MR_ELEC,
        flags1=M1_FLY | M1_BREATHLESS | M1_NOLIMBS | M1_NOHEAD | M1_MINDLESS | M1_NOTAKE,
        flags2=M2_HOSTILE | M2_NEUTER, flags3=M3_INFRAVISIBLE,
        color=HI_ZAP,
        difficulty=8,
    ),
    # 32 — kitten  (line 381)
    MonsterEntry(
        name="kitten",
        symbol=MonsterSymbol.S_FELINE,
        level=2, move_speed=18, ac=6, mr=0, alignment=0,
        generation_mask=G_GENO | 1,
        attacks=(
            (AttackType.AT_BITE, DamageType.AD_PHYS, 1, 6),
        ),
        weight=150, nutrition=150,
        sound=MS_MEW, size=MZ_SMALL,
        resists_mask=0, conveys_mask=0,
        flags1=M1_ANIMAL | M1_NOHANDS | M1_CARNIVORE,
        flags2=M2_WANDER | M2_DOMESTIC, flags3=M3_INFRAVISIBLE,
        color=HI_DOMESTIC,
        difficulty=3,
    ),
    # 33 — housecat  (line 389)
    MonsterEntry(
        name="housecat",
        symbol=MonsterSymbol.S_FELINE,
        level=4, move_speed=16, ac=5, mr=0, alignment=0,
        generation_mask=G_GENO | 1,
        attacks=(
            (AttackType.AT_BITE, DamageType.AD_PHYS, 1, 6),
        ),
        weight=200, nutrition=200,
        sound=MS_MEW, size=MZ_SMALL,
        resists_mask=0, conveys_mask=0,
        flags1=M1_ANIMAL | M1_NOHANDS | M1_CARNIVORE,
        flags2=M2_DOMESTIC, flags3=M3_INFRAVISIBLE,
        color=HI_DOMESTIC,
        difficulty=5,
    ),
    # 34 — jaguar  (line 397)
    MonsterEntry(
        name="jaguar",
        symbol=MonsterSymbol.S_FELINE,
        level=4, move_speed=15, ac=6, mr=0, alignment=0,
        generation_mask=G_GENO | 2,
        attacks=(
            (AttackType.AT_CLAW, DamageType.AD_PHYS, 1, 4),
            (AttackType.AT_CLAW, DamageType.AD_PHYS, 1, 4),
            (AttackType.AT_BITE, DamageType.AD_PHYS, 1, 8),
        ),
        weight=600, nutrition=300,
        sound=MS_GROWL, size=MZ_LARGE,
        resists_mask=0, conveys_mask=0,
        flags1=M1_ANIMAL | M1_NOHANDS | M1_CARNIVORE,
        flags2=M2_HOSTILE, flags3=M3_INFRAVISIBLE,
        color=CLR_BROWN,
        difficulty=6,
    ),
    # 35 — lynx  (line 405)
    MonsterEntry(
        name="lynx",
        symbol=MonsterSymbol.S_FELINE,
        level=5, move_speed=15, ac=6, mr=0, alignment=0,
        generation_mask=G_GENO | 1,
        attacks=(
            (AttackType.AT_CLAW, DamageType.AD_PHYS, 1, 4),
            (AttackType.AT_CLAW, DamageType.AD_PHYS, 1, 4),
            (AttackType.AT_BITE, DamageType.AD_PHYS, 1, 10),
        ),
        weight=600, nutrition=300,
        sound=MS_GROWL, size=MZ_SMALL,
        resists_mask=0, conveys_mask=0,
        flags1=M1_ANIMAL | M1_NOHANDS | M1_CARNIVORE,
        flags2=M2_HOSTILE, flags3=M3_INFRAVISIBLE,
        color=CLR_CYAN,
        difficulty=7,
    ),
    # 36 — panther  (line 413)
    MonsterEntry(
        name="panther",
        symbol=MonsterSymbol.S_FELINE,
        level=5, move_speed=15, ac=6, mr=0, alignment=0,
        generation_mask=G_GENO | 1,
        attacks=(
            (AttackType.AT_CLAW, DamageType.AD_PHYS, 1, 6),
            (AttackType.AT_CLAW, DamageType.AD_PHYS, 1, 6),
            (AttackType.AT_BITE, DamageType.AD_PHYS, 1, 10),
        ),
        weight=600, nutrition=300,
        sound=MS_GROWL, size=MZ_LARGE,
        resists_mask=0, conveys_mask=0,
        flags1=M1_ANIMAL | M1_NOHANDS | M1_CARNIVORE,
        flags2=M2_HOSTILE, flags3=M3_INFRAVISIBLE,
        color=CLR_BLACK,
        difficulty=7,
    ),
    # 37 — large cat  (line 421)
    MonsterEntry(
        name="large cat",
        symbol=MonsterSymbol.S_FELINE,
        level=6, move_speed=15, ac=4, mr=0, alignment=0,
        generation_mask=G_GENO | 1,
        attacks=(
            (AttackType.AT_BITE, DamageType.AD_PHYS, 2, 4),
        ),
        weight=250, nutrition=250,
        sound=MS_MEW, size=MZ_SMALL,
        resists_mask=0, conveys_mask=0,
        flags1=M1_ANIMAL | M1_NOHANDS | M1_CARNIVORE,
        flags2=M2_STRONG | M2_DOMESTIC, flags3=M3_INFRAVISIBLE,
        color=HI_DOMESTIC,
        difficulty=7,
    ),
    # 38 — tiger  (line 429)
    MonsterEntry(
        name="tiger",
        symbol=MonsterSymbol.S_FELINE,
        level=6, move_speed=12, ac=6, mr=0, alignment=0,
        generation_mask=G_GENO | 2,
        attacks=(
            (AttackType.AT_CLAW, DamageType.AD_PHYS, 2, 4),
            (AttackType.AT_CLAW, DamageType.AD_PHYS, 2, 4),
            (AttackType.AT_BITE, DamageType.AD_PHYS, 1, 10),
        ),
        weight=600, nutrition=300,
        sound=MS_GROWL, size=MZ_LARGE,
        resists_mask=0, conveys_mask=0,
        flags1=M1_ANIMAL | M1_NOHANDS | M1_CARNIVORE,
        flags2=M2_HOSTILE, flags3=M3_INFRAVISIBLE,
        color=CLR_YELLOW,
        difficulty=8,
    ),
    # (vendor parity: displacer beast not present in NLE — removed)
    # 40 — gremlin  (line 448)
    MonsterEntry(
        name="gremlin",
        symbol=MonsterSymbol.S_GREMLIN,
        level=5, move_speed=12, ac=2, mr=25, alignment=-9,
        generation_mask=G_GENO | 2,
        attacks=(
            (AttackType.AT_CLAW, DamageType.AD_PHYS, 1, 6),
            (AttackType.AT_CLAW, DamageType.AD_PHYS, 1, 6),
            (AttackType.AT_BITE, DamageType.AD_PHYS, 1, 4),
            (AttackType.AT_CLAW, DamageType.AD_CURS, 0, 0),
        ),
        weight=100, nutrition=20,
        sound=MS_LAUGH, size=MZ_SMALL,
        resists_mask=MR_POISON, conveys_mask=MR_POISON,
        flags1=M1_SWIM | M1_HUMANOID | M1_POIS,
        flags2=M2_STALK, flags3=M3_INFRAVISIBLE,
        color=CLR_GREEN,
        difficulty=8,
    ),
    # 41 — gargoyle  (line 458)
    MonsterEntry(
        name="gargoyle",
        symbol=MonsterSymbol.S_GREMLIN,
        level=6, move_speed=10, ac=-4, mr=0, alignment=-9,
        generation_mask=G_GENO | 2,
        attacks=(
            (AttackType.AT_CLAW, DamageType.AD_PHYS, 2, 6),
            (AttackType.AT_CLAW, DamageType.AD_PHYS, 2, 6),
            (AttackType.AT_BITE, DamageType.AD_PHYS, 2, 4),
        ),
        weight=1000, nutrition=200,
        sound=MS_GRUNT, size=MZ_HUMAN,
        resists_mask=MR_STONE, conveys_mask=MR_STONE,
        flags1=M1_HUMANOID | M1_THICK_HIDE | M1_BREATHLESS,
        flags2=M2_HOSTILE | M2_STRONG, flags3=0,
        color=CLR_BROWN,
        difficulty=8,
    ),
    # 42 — winged gargoyle  (line 466)
    MonsterEntry(
        name="winged gargoyle",
        symbol=MonsterSymbol.S_GREMLIN,
        level=9, move_speed=15, ac=-2, mr=0, alignment=-12,
        generation_mask=G_GENO | 1,
        attacks=(
            (AttackType.AT_CLAW, DamageType.AD_PHYS, 3, 6),
            (AttackType.AT_CLAW, DamageType.AD_PHYS, 3, 6),
            (AttackType.AT_BITE, DamageType.AD_PHYS, 3, 4),
        ),
        weight=1200, nutrition=300,
        sound=MS_GRUNT, size=MZ_HUMAN,
        resists_mask=MR_STONE, conveys_mask=MR_STONE,
        flags1=M1_FLY | M1_HUMANOID | M1_THICK_HIDE | M1_BREATHLESS | M1_OVIPAROUS,
        flags2=M2_LORD | M2_HOSTILE | M2_STRONG | M2_MAGIC, flags3=0,
        color=HI_LORD,
        difficulty=11,
    ),
    # 43 — hobbit  (line 477)
    MonsterEntry(
        name="hobbit",
        symbol=MonsterSymbol.S_HUMANOID,
        level=1, move_speed=9, ac=10, mr=0, alignment=6,
        generation_mask=G_GENO | 2,
        attacks=(
            (AttackType.AT_WEAP, DamageType.AD_PHYS, 1, 6),
        ),
        weight=500, nutrition=200,
        sound=MS_HUMANOID, size=MZ_SMALL,
        resists_mask=0, conveys_mask=0,
        flags1=M1_HUMANOID | M1_OMNIVORE,
        flags2=M2_COLLECT, flags3=M3_INFRAVISIBLE | M3_INFRAVISION,
        color=CLR_GREEN,
        difficulty=2,
    ),
    # 44 — dwarf  (line 485)
    MonsterEntry(
        name="dwarf",
        symbol=MonsterSymbol.S_HUMANOID,
        level=2, move_speed=6, ac=10, mr=10, alignment=4,
        generation_mask=G_GENO | 3,
        attacks=(
            (AttackType.AT_WEAP, DamageType.AD_PHYS, 1, 8),
        ),
        weight=900, nutrition=300,
        sound=MS_HUMANOID, size=MZ_HUMAN,
        resists_mask=0, conveys_mask=0,
        flags1=M1_TUNNEL | M1_NEEDPICK | M1_HUMANOID | M1_OMNIVORE,
        flags2=M2_NOPOLY | M2_DWARF | M2_STRONG | M2_GREEDY | M2_JEWELS | M2_COLLECT,
        flags3=M3_INFRAVISIBLE | M3_INFRAVISION,
        color=CLR_RED,
        difficulty=4,
    ),
    # 45 — bugbear  (line 494)
    MonsterEntry(
        name="bugbear",
        symbol=MonsterSymbol.S_HUMANOID,
        level=3, move_speed=9, ac=5, mr=0, alignment=-6,
        generation_mask=G_GENO | 1,
        attacks=(
            (AttackType.AT_WEAP, DamageType.AD_PHYS, 2, 4),
        ),
        weight=1250, nutrition=250,
        sound=MS_GROWL, size=MZ_LARGE,
        resists_mask=0, conveys_mask=0,
        flags1=M1_HUMANOID | M1_OMNIVORE,
        flags2=M2_STRONG | M2_COLLECT, flags3=M3_INFRAVISIBLE | M3_INFRAVISION,
        color=CLR_BROWN,
        difficulty=5,
    ),
    # 46 — dwarf lord/lady/leader  (line 502)
    MonsterEntry(
        name="dwarf lord",
        symbol=MonsterSymbol.S_HUMANOID,
        level=4, move_speed=6, ac=10, mr=10, alignment=5,
        generation_mask=G_GENO | 2,
        attacks=(
            (AttackType.AT_WEAP, DamageType.AD_PHYS, 2, 4),
            (AttackType.AT_WEAP, DamageType.AD_PHYS, 2, 4),
        ),
        weight=900, nutrition=300,
        sound=MS_HUMANOID, size=MZ_HUMAN,
        resists_mask=0, conveys_mask=0,
        flags1=M1_TUNNEL | M1_NEEDPICK | M1_HUMANOID | M1_OMNIVORE,
        flags2=M2_DWARF | M2_STRONG | M2_LORD | M2_MALE | M2_GREEDY | M2_JEWELS | M2_COLLECT,
        flags3=M3_INFRAVISIBLE | M3_INFRAVISION,
        color=CLR_BLUE,
        difficulty=6,
    ),
    # 47 — dwarf king/queen/ruler  (line 511)
    MonsterEntry(
        name="dwarf king",
        symbol=MonsterSymbol.S_HUMANOID,
        level=6, move_speed=6, ac=10, mr=20, alignment=6,
        generation_mask=G_GENO | 1,
        attacks=(
            (AttackType.AT_WEAP, DamageType.AD_PHYS, 2, 6),
            (AttackType.AT_WEAP, DamageType.AD_PHYS, 2, 6),
        ),
        weight=900, nutrition=300,
        sound=MS_HUMANOID, size=MZ_HUMAN,
        resists_mask=0, conveys_mask=0,
        flags1=M1_TUNNEL | M1_NEEDPICK | M1_HUMANOID | M1_OMNIVORE,
        flags2=M2_DWARF | M2_STRONG | M2_PRINCE | M2_MALE | M2_GREEDY | M2_JEWELS | M2_COLLECT,
        flags3=M3_INFRAVISIBLE | M3_INFRAVISION,
        color=HI_LORD,
        difficulty=8,
    ),
    # 48 — mind flayer  (line 521)
    MonsterEntry(
        name="mind flayer",
        symbol=MonsterSymbol.S_HUMANOID,
        level=9, move_speed=12, ac=5, mr=90, alignment=-8,
        generation_mask=G_GENO | 1,
        attacks=(
            (AttackType.AT_WEAP, DamageType.AD_PHYS, 1, 4),
            (AttackType.AT_TENT, DamageType.AD_DRIN, 2, 1),
            (AttackType.AT_TENT, DamageType.AD_DRIN, 2, 1),
            (AttackType.AT_TENT, DamageType.AD_DRIN, 2, 1),
        ),
        weight=1450, nutrition=400,
        sound=MS_HISS, size=MZ_HUMAN,
        resists_mask=0, conveys_mask=0,
        flags1=M1_HUMANOID | M1_FLY | M1_SEE_INVIS | M1_OMNIVORE,
        flags2=M2_HOSTILE | M2_NASTY | M2_GREEDY | M2_JEWELS | M2_COLLECT,
        flags3=M3_INFRAVISIBLE | M3_INFRAVISION,
        color=CLR_MAGENTA,
        difficulty=13,
    ),
    # 49 — master mind flayer  (line 531)
    MonsterEntry(
        name="master mind flayer",
        symbol=MonsterSymbol.S_HUMANOID,
        level=13, move_speed=12, ac=0, mr=90, alignment=-8,
        generation_mask=G_GENO | 1,
        attacks=(
            (AttackType.AT_WEAP, DamageType.AD_PHYS, 1, 8),
            (AttackType.AT_TENT, DamageType.AD_DRIN, 2, 1),
            (AttackType.AT_TENT, DamageType.AD_DRIN, 2, 1),
            (AttackType.AT_TENT, DamageType.AD_DRIN, 2, 1),
            (AttackType.AT_TENT, DamageType.AD_DRIN, 2, 1),
            (AttackType.AT_TENT, DamageType.AD_DRIN, 2, 1),
        ),
        weight=1450, nutrition=400,
        sound=MS_HISS, size=MZ_HUMAN,
        resists_mask=0, conveys_mask=0,
        flags1=M1_HUMANOID | M1_FLY | M1_SEE_INVIS | M1_OMNIVORE,
        flags2=M2_HOSTILE | M2_NASTY | M2_GREEDY | M2_JEWELS | M2_COLLECT,
        flags3=M3_INFRAVISIBLE | M3_INFRAVISION,
        color=CLR_MAGENTA,
        difficulty=19,
    ),
    # 50 — manes  (line 544)
    MonsterEntry(
        name="manes",
        symbol=MonsterSymbol.S_IMP,
        level=1, move_speed=3, ac=7, mr=0, alignment=-7,
        generation_mask=G_GENO | G_LGROUP | G_NOCORPSE | 1,
        attacks=(
            (AttackType.AT_CLAW, DamageType.AD_PHYS, 1, 3),
            (AttackType.AT_CLAW, DamageType.AD_PHYS, 1, 3),
            (AttackType.AT_BITE, DamageType.AD_PHYS, 1, 4),
        ),
        weight=100, nutrition=100,
        sound=MS_SILENT, size=MZ_SMALL,
        resists_mask=MR_SLEEP | MR_POISON, conveys_mask=0,
        flags1=M1_POIS,
        flags2=M2_HOSTILE | M2_STALK, flags3=M3_INFRAVISIBLE | M3_INFRAVISION,
        color=CLR_RED,
        difficulty=3,
    ),
    # 51 — homunculus  (line 551)
    MonsterEntry(
        name="homunculus",
        symbol=MonsterSymbol.S_IMP,
        level=2, move_speed=12, ac=6, mr=10, alignment=-7,
        generation_mask=G_GENO | 2,
        attacks=(
            (AttackType.AT_BITE, DamageType.AD_SLEE, 1, 3),
        ),
        weight=60, nutrition=100,
        sound=MS_SILENT, size=MZ_TINY,
        resists_mask=MR_SLEEP | MR_POISON, conveys_mask=MR_SLEEP | MR_POISON,
        flags1=M1_FLY | M1_POIS,
        flags2=M2_STALK, flags3=M3_INFRAVISIBLE | M3_INFRAVISION,
        color=CLR_GREEN,
        difficulty=3,
    ),
    # 52 — imp  (line 559)
    MonsterEntry(
        name="imp",
        symbol=MonsterSymbol.S_IMP,
        level=3, move_speed=12, ac=2, mr=20, alignment=-7,
        generation_mask=G_GENO | 1,
        attacks=(
            (AttackType.AT_CLAW, DamageType.AD_PHYS, 1, 4),
        ),
        weight=20, nutrition=10,
        sound=MS_CUSS, size=MZ_TINY,
        resists_mask=0, conveys_mask=0,
        flags1=M1_REGEN,
        flags2=M2_WANDER | M2_STALK, flags3=M3_INFRAVISIBLE | M3_INFRAVISION,
        color=CLR_RED,
        difficulty=4,
    ),
    # 53 — lemure  (line 566)
    MonsterEntry(
        name="lemure",
        symbol=MonsterSymbol.S_IMP,
        level=3, move_speed=3, ac=7, mr=0, alignment=-7,
        generation_mask=G_HELL | G_GENO | G_LGROUP | G_NOCORPSE | 1,
        attacks=(
            (AttackType.AT_CLAW, DamageType.AD_PHYS, 1, 3),
        ),
        weight=150, nutrition=100,
        sound=MS_SILENT, size=MZ_MEDIUM,
        resists_mask=MR_SLEEP | MR_POISON, conveys_mask=MR_SLEEP,
        flags1=M1_POIS | M1_REGEN,
        flags2=M2_HOSTILE | M2_WANDER | M2_STALK | M2_NEUTER,
        flags3=M3_INFRAVISIBLE | M3_INFRAVISION,
        color=CLR_BROWN,
        difficulty=5,
    ),
    # 54 — quasit  (line 574)
    MonsterEntry(
        name="quasit",
        symbol=MonsterSymbol.S_IMP,
        level=3, move_speed=15, ac=2, mr=20, alignment=-7,
        generation_mask=G_GENO | 2,
        attacks=(
            (AttackType.AT_CLAW, DamageType.AD_DRDX, 1, 2),
            (AttackType.AT_CLAW, DamageType.AD_DRDX, 1, 2),
            (AttackType.AT_BITE, DamageType.AD_PHYS, 1, 4),
        ),
        weight=200, nutrition=200,
        sound=MS_SILENT, size=MZ_SMALL,
        resists_mask=MR_POISON, conveys_mask=MR_POISON,
        flags1=M1_REGEN,
        flags2=M2_STALK, flags3=M3_INFRAVISIBLE | M3_INFRAVISION,
        color=CLR_BLUE,
        difficulty=7,
    ),
    # 55 — tengu  (line 581)
    MonsterEntry(
        name="tengu",
        symbol=MonsterSymbol.S_IMP,
        level=6, move_speed=13, ac=5, mr=30, alignment=7,
        generation_mask=G_GENO | 3,
        attacks=(
            (AttackType.AT_BITE, DamageType.AD_PHYS, 1, 7),
        ),
        weight=300, nutrition=200,
        sound=MS_SQAWK, size=MZ_SMALL,
        resists_mask=MR_POISON, conveys_mask=MR_POISON,
        flags1=M1_TPORT | M1_TPORT_CNTRL,
        flags2=M2_STALK, flags3=M3_INFRAVISIBLE | M3_INFRAVISION,
        color=CLR_CYAN,
        difficulty=7,
    ),
    # 56 — blue jelly  (line 591)
    MonsterEntry(
        name="blue jelly",
        symbol=MonsterSymbol.S_JELLY,
        level=4, move_speed=0, ac=8, mr=10, alignment=0,
        generation_mask=G_GENO | 2,
        attacks=(
            (AttackType.AT_NONE, DamageType.AD_COLD, 0, 6),
        ),
        weight=WT_JELLY, nutrition=20,
        sound=MS_SILENT, size=MZ_MEDIUM,
        resists_mask=MR_COLD | MR_POISON, conveys_mask=MR_COLD | MR_POISON,
        flags1=M1_BREATHLESS | M1_AMORPHOUS | M1_NOEYES | M1_NOLIMBS | M1_NOHEAD | M1_MINDLESS | M1_NOTAKE,
        flags2=M2_HOSTILE | M2_NEUTER, flags3=0,
        color=CLR_BLUE,
        difficulty=5,
    ),
    # 57 — spotted jelly  (line 601)
    MonsterEntry(
        name="spotted jelly",
        symbol=MonsterSymbol.S_JELLY,
        level=5, move_speed=0, ac=8, mr=10, alignment=0,
        generation_mask=G_GENO | 1,
        attacks=(
            (AttackType.AT_NONE, DamageType.AD_ACID, 0, 6),
        ),
        weight=WT_JELLY, nutrition=20,
        sound=MS_SILENT, size=MZ_MEDIUM,
        resists_mask=MR_ACID | MR_STONE, conveys_mask=0,
        flags1=M1_BREATHLESS | M1_AMORPHOUS | M1_NOEYES | M1_NOLIMBS | M1_NOHEAD | M1_MINDLESS | M1_ACID | M1_NOTAKE,
        flags2=M2_HOSTILE | M2_NEUTER, flags3=0,
        color=CLR_GREEN,
        difficulty=6,
    ),
    # 58 — ochre jelly  (line 611)
    MonsterEntry(
        name="ochre jelly",
        symbol=MonsterSymbol.S_JELLY,
        level=6, move_speed=3, ac=8, mr=20, alignment=0,
        generation_mask=G_GENO | 2,
        attacks=(
            (AttackType.AT_ENGL, DamageType.AD_ACID, 3, 6),
            (AttackType.AT_NONE, DamageType.AD_ACID, 3, 6),
        ),
        weight=WT_JELLY, nutrition=20,
        sound=MS_SILENT, size=MZ_MEDIUM,
        resists_mask=MR_ACID | MR_STONE, conveys_mask=0,
        flags1=M1_BREATHLESS | M1_AMORPHOUS | M1_NOEYES | M1_NOLIMBS | M1_NOHEAD | M1_MINDLESS | M1_ACID | M1_NOTAKE,
        flags2=M2_HOSTILE | M2_NEUTER, flags3=0,
        color=CLR_BROWN,
        difficulty=8,
    ),
    # 59 — kobold  (line 624)
    MonsterEntry(
        name="kobold",
        symbol=MonsterSymbol.S_KOBOLD,
        level=0, move_speed=6, ac=10, mr=0, alignment=-2,
        generation_mask=G_GENO | 1,
        attacks=(
            (AttackType.AT_WEAP, DamageType.AD_PHYS, 1, 4),
        ),
        weight=400, nutrition=100,
        sound=MS_ORC, size=MZ_SMALL,
        resists_mask=MR_POISON, conveys_mask=0,
        flags1=M1_HUMANOID | M1_POIS | M1_OMNIVORE,
        flags2=M2_HOSTILE | M2_COLLECT, flags3=M3_INFRAVISIBLE | M3_INFRAVISION,
        color=CLR_BROWN,
        difficulty=1,
    ),
    # 60 — large kobold  (line 632)
    MonsterEntry(
        name="large kobold",
        symbol=MonsterSymbol.S_KOBOLD,
        level=1, move_speed=6, ac=10, mr=0, alignment=-3,
        generation_mask=G_GENO | 1,
        attacks=(
            (AttackType.AT_WEAP, DamageType.AD_PHYS, 1, 6),
        ),
        weight=450, nutrition=150,
        sound=MS_ORC, size=MZ_SMALL,
        resists_mask=MR_POISON, conveys_mask=0,
        flags1=M1_HUMANOID | M1_POIS | M1_OMNIVORE,
        flags2=M2_HOSTILE | M2_COLLECT, flags3=M3_INFRAVISIBLE | M3_INFRAVISION,
        color=CLR_RED,
        difficulty=2,
    ),
    # 61 — kobold lord/lady/leader  (line 640)
    MonsterEntry(
        name="kobold lord",
        symbol=MonsterSymbol.S_KOBOLD,
        level=2, move_speed=6, ac=10, mr=0, alignment=-4,
        generation_mask=G_GENO | 1,
        attacks=(
            (AttackType.AT_WEAP, DamageType.AD_PHYS, 2, 4),
        ),
        weight=500, nutrition=200,
        sound=MS_ORC, size=MZ_SMALL,
        resists_mask=MR_POISON, conveys_mask=0,
        flags1=M1_HUMANOID | M1_POIS | M1_OMNIVORE,
        flags2=M2_HOSTILE | M2_LORD | M2_MALE | M2_COLLECT,
        flags3=M3_INFRAVISIBLE | M3_INFRAVISION,
        color=HI_LORD,
        difficulty=3,
    ),
    # 62 — kobold shaman  (line 649)
    MonsterEntry(
        name="kobold shaman",
        symbol=MonsterSymbol.S_KOBOLD,
        level=2, move_speed=6, ac=6, mr=10, alignment=-4,
        generation_mask=G_GENO | 1,
        attacks=(
            (AttackType.AT_MAGC, DamageType.AD_SPEL, 0, 0),
        ),
        weight=450, nutrition=150,
        sound=MS_ORC, size=MZ_SMALL,
        resists_mask=MR_POISON, conveys_mask=0,
        flags1=M1_HUMANOID | M1_POIS | M1_OMNIVORE,
        flags2=M2_HOSTILE | M2_MAGIC,
        flags3=M3_INFRAVISIBLE | M3_INFRAVISION,
        color=HI_ZAP,
        difficulty=4,
    ),
    # 63 — leprechaun  (line 660)
    MonsterEntry(
        name="leprechaun",
        symbol=MonsterSymbol.S_LEPRECHAUN,
        level=5, move_speed=15, ac=8, mr=20, alignment=0,
        generation_mask=G_GENO | 4,
        attacks=(
            (AttackType.AT_CLAW, DamageType.AD_SGLD, 1, 2),
        ),
        weight=60, nutrition=30,
        sound=MS_LAUGH, size=MZ_TINY,
        resists_mask=0, conveys_mask=0,
        flags1=M1_HUMANOID | M1_TPORT,
        flags2=M2_HOSTILE | M2_GREEDY, flags3=M3_INFRAVISIBLE,
        color=CLR_GREEN,
        difficulty=4,
    ),
    # 64 — small mimic  (line 670)
    MonsterEntry(
        name="small mimic",
        symbol=MonsterSymbol.S_MIMIC,
        level=7, move_speed=3, ac=7, mr=0, alignment=0,
        generation_mask=G_GENO | 2,
        attacks=(
            (AttackType.AT_CLAW, DamageType.AD_PHYS, 3, 4),
        ),
        weight=300, nutrition=200,
        sound=MS_SILENT, size=MZ_MEDIUM,
        resists_mask=MR_ACID, conveys_mask=0,
        flags1=M1_BREATHLESS | M1_AMORPHOUS | M1_HIDE | M1_ANIMAL | M1_NOEYES | M1_NOHEAD | M1_NOLIMBS | M1_THICK_HIDE | M1_CARNIVORE,
        flags2=M2_HOSTILE, flags3=0,
        color=CLR_BROWN,
        difficulty=8,
    ),
)
